# Generated by wayland-nim-scanner 1.23.1
{.warning[UnusedImport]:off.}
import wayland/native/common
import wayland/protocols/wayland/code as wayland_code

var fullscreenShellUnstableV1_types: array[8, ptr Interface]
type ZwpFullscreenShellModeFeedbackV1* = object
type ZwpFullscreenShellV1* = object

let
  zwp_fullscreen_shell_v1_requests {.exportc.} = [
    Message(name: "release", signature: "", types: addr fullscreen_shell_unstable_v1_types[0]),
    Message(name: "present_surface", signature: "?ou?o", types: addr fullscreen_shell_unstable_v1_types[1]),
    Message(name: "present_surface_for_mode", signature: "ooin", types: addr fullscreen_shell_unstable_v1_types[4]),
  ]

  zwp_fullscreen_shell_v1_events {.exportc.} = [
    Message(name: "capability", signature: "u", types: addr fullscreen_shell_unstable_v1_types[0]),
  ]

  zwp_fullscreen_shell_v1_interface* {.exportc.} = Interface(
    name: "zwp_fullscreen_shell_v1",
    version: 1,
    method_count: 3,
    methods: addr zwp_fullscreen_shell_v1_requests[0],
    event_count: 1,
    events: addr zwp_fullscreen_shell_v1_events[0],
  )

  zwp_fullscreen_shell_mode_feedback_v1_events {.exportc.} = [
    Message(name: "mode_successful", signature: "", types: addr fullscreen_shell_unstable_v1_types[0]),
    Message(name: "mode_failed", signature: "", types: addr fullscreen_shell_unstable_v1_types[0]),
    Message(name: "present_cancelled", signature: "", types: addr fullscreen_shell_unstable_v1_types[0]),
  ]

  zwp_fullscreen_shell_mode_feedback_v1_interface* {.exportc.} = Interface(
    name: "zwp_fullscreen_shell_mode_feedback_v1",
    version: 1,
    event_count: 3,
    events: addr zwp_fullscreen_shell_mode_feedback_v1_events[0],
  )


type ZwpFullscreenShellV1Capability* {.size: sizeof(uint32).} = enum
  capability_arbitrary_modes = 1
  capability_cursor_plane = 2
func since*(e: ZwpFullscreenShellV1Capability): int =
  case e
  of capability_arbitrary_modes: 1
  of capability_cursor_plane: 1
proc isValid*(e: ZwpFullscreenShellV1Capability; version: int): bool =
  version >= e.since

type ZwpFullscreenShellV1PresentMethod* {.size: sizeof(uint32).} = enum
  present_method_default = 0
  present_method_center = 1
  present_method_zoom = 2
  present_method_zoom_crop = 3
  present_method_stretch = 4
func since*(e: ZwpFullscreenShellV1PresentMethod): int =
  case e
  of present_method_default: 1
  of present_method_center: 1
  of present_method_zoom: 1
  of present_method_zoom_crop: 1
  of present_method_stretch: 1
proc isValid*(e: ZwpFullscreenShellV1PresentMethod; version: int): bool =
  version >= e.since

type ZwpFullscreenShellV1Error* {.size: sizeof(uint32).} = enum
  error_invalid_method = 0
  error_role = 1
func since*(e: ZwpFullscreenShellV1Error): int =
  case e
  of error_invalid_method: 1
  of error_role: 1
proc isValid*(e: ZwpFullscreenShellV1Error; version: int): bool =
  version >= e.since

type ZwpFullscreenShellV1Event* {.size: sizeof(uint32).} = enum
  ZwpFullscreenShellV1Event_capability
proc since*(e: ZwpFullscreenShellV1Event): int =
  case e
  of ZwpFullscreenShellV1Event_capability: 1

type ZwpFullscreenShellV1Request* {.size: sizeof(uint32).} = enum
  ZwpFullscreenShellV1Request_release
  ZwpFullscreenShellV1Request_present_surface
  ZwpFullscreenShellV1Request_present_surface_for_mode
proc since*(e: ZwpFullscreenShellV1Request): int =
  case e
  of ZwpFullscreenShellV1Request_release: 1
  of ZwpFullscreenShellV1Request_present_surface: 1
  of ZwpFullscreenShellV1Request_present_surface_for_mode: 1

type ZwpFullscreenShellModeFeedbackV1Event* {.size: sizeof(uint32).} = enum
  ZwpFullscreenShellModeFeedbackV1Event_mode_successful
  ZwpFullscreenShellModeFeedbackV1Event_mode_failed
  ZwpFullscreenShellModeFeedbackV1Event_present_cancelled
proc since*(e: ZwpFullscreenShellModeFeedbackV1Event): int =
  case e
  of ZwpFullscreenShellModeFeedbackV1Event_mode_successful: 1
  of ZwpFullscreenShellModeFeedbackV1Event_mode_failed: 1
  of ZwpFullscreenShellModeFeedbackV1Event_present_cancelled: 1

fullscreenShellUnstableV1_types = [
  nil,
  addr wl_surface_interface,
  nil,
  addr wl_output_interface,
  addr wl_surface_interface,
  addr wl_output_interface,
  nil,
  addr zwp_fullscreen_shell_mode_feedback_v1_interface,
]


