# Generated by wayland-nim-scanner 1.23.1
{.warning[UnusedImport]:off.}
import wayland/native/common
import wayland/protocols/wayland/code as wayland_code

var commitTimingV1_types: array[5, ptr Interface]
type WpCommitTimerV1* = object
type WpCommitTimingManagerV1* = object

let
  wp_commit_timing_manager_v1_requests {.exportc.} = [
    Message(name: "destroy", signature: "", types: addr commit_timing_v1_types[0]),
    Message(name: "get_timer", signature: "no", types: addr commit_timing_v1_types[3]),
  ]

  wp_commit_timing_manager_v1_interface* {.exportc.} = Interface(
    name: "wp_commit_timing_manager_v1",
    version: 1,
    method_count: 2,
    methods: addr wp_commit_timing_manager_v1_requests[0],
  )

  wp_commit_timer_v1_requests {.exportc.} = [
    Message(name: "set_timestamp", signature: "uuu", types: addr commit_timing_v1_types[0]),
    Message(name: "destroy", signature: "", types: addr commit_timing_v1_types[0]),
  ]

  wp_commit_timer_v1_interface* {.exportc.} = Interface(
    name: "wp_commit_timer_v1",
    version: 1,
    method_count: 2,
    methods: addr wp_commit_timer_v1_requests[0],
  )


type WpCommitTimingManagerV1Error* {.size: sizeof(uint32).} = enum
  error_commit_timer_exists = 0
func since*(e: WpCommitTimingManagerV1Error): int =
  case e
  of error_commit_timer_exists: 1
proc isValid*(e: WpCommitTimingManagerV1Error; version: int): bool =
  version >= e.since

type WpCommitTimerV1Error* {.size: sizeof(uint32).} = enum
  error_invalid_timestamp = 0
  error_timestamp_exists = 1
  error_surface_destroyed = 2
func since*(e: WpCommitTimerV1Error): int =
  case e
  of error_invalid_timestamp: 1
  of error_timestamp_exists: 1
  of error_surface_destroyed: 1
proc isValid*(e: WpCommitTimerV1Error; version: int): bool =
  version >= e.since

type WpCommitTimingManagerV1Request* {.size: sizeof(uint32).} = enum
  WpCommitTimingManagerV1Request_destroy
  WpCommitTimingManagerV1Request_get_timer
proc since*(e: WpCommitTimingManagerV1Request): int =
  case e
  of WpCommitTimingManagerV1Request_destroy: 1
  of WpCommitTimingManagerV1Request_get_timer: 1

type WpCommitTimerV1Request* {.size: sizeof(uint32).} = enum
  WpCommitTimerV1Request_set_timestamp
  WpCommitTimerV1Request_destroy
proc since*(e: WpCommitTimerV1Request): int =
  case e
  of WpCommitTimerV1Request_set_timestamp: 1
  of WpCommitTimerV1Request_destroy: 1

commitTimingV1_types = [
  nil,
  nil,
  nil,
  addr wp_commit_timer_v1_interface,
  addr wl_surface_interface,
]


