# Generated by wayland-nim-scanner 1.23.1
{.warning[UnusedImport]:off.}
import wayland/native/common
import wayland/protocols/wayland/code as wayland_code

var idleInhibitUnstableV1_types: array[2, ptr Interface]
type ZwpIdleInhibitManagerV1* = object
type ZwpIdleInhibitorV1* = object

let
  zwp_idle_inhibit_manager_v1_requests {.exportc.} = [
    Message(name: "destroy", signature: "", types: addr idle_inhibit_unstable_v1_types[0]),
    Message(name: "create_inhibitor", signature: "no", types: addr idle_inhibit_unstable_v1_types[0]),
  ]

  zwp_idle_inhibit_manager_v1_interface* {.exportc.} = Interface(
    name: "zwp_idle_inhibit_manager_v1",
    version: 1,
    method_count: 2,
    methods: addr zwp_idle_inhibit_manager_v1_requests[0],
  )

  zwp_idle_inhibitor_v1_requests {.exportc.} = [
    Message(name: "destroy", signature: "", types: addr idle_inhibit_unstable_v1_types[0]),
  ]

  zwp_idle_inhibitor_v1_interface* {.exportc.} = Interface(
    name: "zwp_idle_inhibitor_v1",
    version: 1,
    method_count: 1,
    methods: addr zwp_idle_inhibitor_v1_requests[0],
  )


type ZwpIdleInhibitManagerV1Request* {.size: sizeof(uint32).} = enum
  ZwpIdleInhibitManagerV1Request_destroy
  ZwpIdleInhibitManagerV1Request_create_inhibitor
proc since*(e: ZwpIdleInhibitManagerV1Request): int =
  case e
  of ZwpIdleInhibitManagerV1Request_destroy: 1
  of ZwpIdleInhibitManagerV1Request_create_inhibitor: 1

type ZwpIdleInhibitorV1Request* {.size: sizeof(uint32).} = enum
  ZwpIdleInhibitorV1Request_destroy
proc since*(e: ZwpIdleInhibitorV1Request): int =
  case e
  of ZwpIdleInhibitorV1Request_destroy: 1

idleInhibitUnstableV1_types = [
  addr zwp_idle_inhibitor_v1_interface,
  addr wl_surface_interface,
]


