# Generated by wayland-nim-scanner 1.23.1
{.warning[UnusedImport]:off.}
import wayland/native/common
import wayland/protocols/wayland/code as wayland_code

var pointerGesturesUnstableV1_types: array[23, ptr Interface]
type ZwpPointerGestureHoldV1* = object
type ZwpPointerGesturePinchV1* = object
type ZwpPointerGestureSwipeV1* = object
type ZwpPointerGesturesV1* = object

let
  zwp_pointer_gestures_v1_requests {.exportc.} = [
    Message(name: "get_swipe_gesture", signature: "no", types: addr pointer_gestures_unstable_v1_types[5]),
    Message(name: "get_pinch_gesture", signature: "no", types: addr pointer_gestures_unstable_v1_types[7]),
    Message(name: "release", signature: "2", types: addr pointer_gestures_unstable_v1_types[0]),
    Message(name: "get_hold_gesture", signature: "3no", types: addr pointer_gestures_unstable_v1_types[9]),
  ]

  zwp_pointer_gestures_v1_interface* {.exportc.} = Interface(
    name: "zwp_pointer_gestures_v1",
    version: 3,
    method_count: 4,
    methods: addr zwp_pointer_gestures_v1_requests[0],
  )

  zwp_pointer_gesture_swipe_v1_requests {.exportc.} = [
    Message(name: "destroy", signature: "", types: addr pointer_gestures_unstable_v1_types[0]),
  ]

  zwp_pointer_gesture_swipe_v1_events {.exportc.} = [
    Message(name: "begin", signature: "uuou", types: addr pointer_gestures_unstable_v1_types[11]),
    Message(name: "update", signature: "uff", types: addr pointer_gestures_unstable_v1_types[0]),
    Message(name: "end", signature: "uui", types: addr pointer_gestures_unstable_v1_types[0]),
  ]

  zwp_pointer_gesture_swipe_v1_interface* {.exportc.} = Interface(
    name: "zwp_pointer_gesture_swipe_v1",
    version: 2,
    method_count: 1,
    methods: addr zwp_pointer_gesture_swipe_v1_requests[0],
    event_count: 3,
    events: addr zwp_pointer_gesture_swipe_v1_events[0],
  )

  zwp_pointer_gesture_pinch_v1_requests {.exportc.} = [
    Message(name: "destroy", signature: "", types: addr pointer_gestures_unstable_v1_types[0]),
  ]

  zwp_pointer_gesture_pinch_v1_events {.exportc.} = [
    Message(name: "begin", signature: "uuou", types: addr pointer_gestures_unstable_v1_types[15]),
    Message(name: "update", signature: "uffff", types: addr pointer_gestures_unstable_v1_types[0]),
    Message(name: "end", signature: "uui", types: addr pointer_gestures_unstable_v1_types[0]),
  ]

  zwp_pointer_gesture_pinch_v1_interface* {.exportc.} = Interface(
    name: "zwp_pointer_gesture_pinch_v1",
    version: 2,
    method_count: 1,
    methods: addr zwp_pointer_gesture_pinch_v1_requests[0],
    event_count: 3,
    events: addr zwp_pointer_gesture_pinch_v1_events[0],
  )

  zwp_pointer_gesture_hold_v1_requests {.exportc.} = [
    Message(name: "destroy", signature: "3", types: addr pointer_gestures_unstable_v1_types[0]),
  ]

  zwp_pointer_gesture_hold_v1_events {.exportc.} = [
    Message(name: "begin", signature: "3uuou", types: addr pointer_gestures_unstable_v1_types[19]),
    Message(name: "end", signature: "3uui", types: addr pointer_gestures_unstable_v1_types[0]),
  ]

  zwp_pointer_gesture_hold_v1_interface* {.exportc.} = Interface(
    name: "zwp_pointer_gesture_hold_v1",
    version: 3,
    method_count: 1,
    methods: addr zwp_pointer_gesture_hold_v1_requests[0],
    event_count: 2,
    events: addr zwp_pointer_gesture_hold_v1_events[0],
  )


type ZwpPointerGesturesV1Request* {.size: sizeof(uint32).} = enum
  ZwpPointerGesturesV1Request_get_swipe_gesture
  ZwpPointerGesturesV1Request_get_pinch_gesture
  ZwpPointerGesturesV1Request_release
  ZwpPointerGesturesV1Request_get_hold_gesture
proc since*(e: ZwpPointerGesturesV1Request): int =
  case e
  of ZwpPointerGesturesV1Request_get_swipe_gesture: 1
  of ZwpPointerGesturesV1Request_get_pinch_gesture: 1
  of ZwpPointerGesturesV1Request_release: 2
  of ZwpPointerGesturesV1Request_get_hold_gesture: 3

type ZwpPointerGestureSwipeV1Event* {.size: sizeof(uint32).} = enum
  ZwpPointerGestureSwipeV1Event_begin
  ZwpPointerGestureSwipeV1Event_update
  ZwpPointerGestureSwipeV1Event_end
proc since*(e: ZwpPointerGestureSwipeV1Event): int =
  case e
  of ZwpPointerGestureSwipeV1Event_begin: 1
  of ZwpPointerGestureSwipeV1Event_update: 1
  of ZwpPointerGestureSwipeV1Event_end: 1

type ZwpPointerGestureSwipeV1Request* {.size: sizeof(uint32).} = enum
  ZwpPointerGestureSwipeV1Request_destroy
proc since*(e: ZwpPointerGestureSwipeV1Request): int =
  case e
  of ZwpPointerGestureSwipeV1Request_destroy: 1

type ZwpPointerGesturePinchV1Event* {.size: sizeof(uint32).} = enum
  ZwpPointerGesturePinchV1Event_begin
  ZwpPointerGesturePinchV1Event_update
  ZwpPointerGesturePinchV1Event_end
proc since*(e: ZwpPointerGesturePinchV1Event): int =
  case e
  of ZwpPointerGesturePinchV1Event_begin: 1
  of ZwpPointerGesturePinchV1Event_update: 1
  of ZwpPointerGesturePinchV1Event_end: 1

type ZwpPointerGesturePinchV1Request* {.size: sizeof(uint32).} = enum
  ZwpPointerGesturePinchV1Request_destroy
proc since*(e: ZwpPointerGesturePinchV1Request): int =
  case e
  of ZwpPointerGesturePinchV1Request_destroy: 1

type ZwpPointerGestureHoldV1Event* {.size: sizeof(uint32).} = enum
  ZwpPointerGestureHoldV1Event_begin
  ZwpPointerGestureHoldV1Event_end
proc since*(e: ZwpPointerGestureHoldV1Event): int =
  case e
  of ZwpPointerGestureHoldV1Event_begin: 3
  of ZwpPointerGestureHoldV1Event_end: 3

type ZwpPointerGestureHoldV1Request* {.size: sizeof(uint32).} = enum
  ZwpPointerGestureHoldV1Request_destroy
proc since*(e: ZwpPointerGestureHoldV1Request): int =
  case e
  of ZwpPointerGestureHoldV1Request_destroy: 3

pointerGesturesUnstableV1_types = [
  nil,
  nil,
  nil,
  nil,
  nil,
  addr zwp_pointer_gesture_swipe_v1_interface,
  addr wl_pointer_interface,
  addr zwp_pointer_gesture_pinch_v1_interface,
  addr wl_pointer_interface,
  addr zwp_pointer_gesture_hold_v1_interface,
  addr wl_pointer_interface,
  nil,
  nil,
  addr wl_surface_interface,
  nil,
  nil,
  nil,
  addr wl_surface_interface,
  nil,
  nil,
  nil,
  addr wl_surface_interface,
  nil,
]


