# Generated by wayland-nim-scanner 1.23.1
{.warning[UnusedImport]:off.}
import wayland/native/common
import wayland/protocols/wayland/code as wayland_code

var colorRepresentationV1_types: array[4, ptr Interface]
type WpColorRepresentationManagerV1* = object
type WpColorRepresentationSurfaceV1* = object

let
  wp_color_representation_manager_v1_requests {.exportc.} = [
    Message(name: "destroy", signature: "", types: addr color_representation_v1_types[0]),
    Message(name: "get_surface", signature: "no", types: addr color_representation_v1_types[2]),
  ]

  wp_color_representation_manager_v1_events {.exportc.} = [
    Message(name: "supported_alpha_mode", signature: "u", types: addr color_representation_v1_types[0]),
    Message(name: "supported_coefficients_and_ranges", signature: "uu", types: addr color_representation_v1_types[0]),
    Message(name: "done", signature: "", types: addr color_representation_v1_types[0]),
  ]

  wp_color_representation_manager_v1_interface* {.exportc.} = Interface(
    name: "wp_color_representation_manager_v1",
    version: 1,
    method_count: 2,
    methods: addr wp_color_representation_manager_v1_requests[0],
    event_count: 3,
    events: addr wp_color_representation_manager_v1_events[0],
  )

  wp_color_representation_surface_v1_requests {.exportc.} = [
    Message(name: "destroy", signature: "", types: addr color_representation_v1_types[0]),
    Message(name: "set_alpha_mode", signature: "u", types: addr color_representation_v1_types[0]),
    Message(name: "set_coefficients_and_range", signature: "uu", types: addr color_representation_v1_types[0]),
    Message(name: "set_chroma_location", signature: "u", types: addr color_representation_v1_types[0]),
  ]

  wp_color_representation_surface_v1_interface* {.exportc.} = Interface(
    name: "wp_color_representation_surface_v1",
    version: 1,
    method_count: 4,
    methods: addr wp_color_representation_surface_v1_requests[0],
  )


type WpColorRepresentationManagerV1Error* {.size: sizeof(uint32).} = enum
  error_surface_exists = 1
func since*(e: WpColorRepresentationManagerV1Error): int =
  case e
  of error_surface_exists: 1
proc isValid*(e: WpColorRepresentationManagerV1Error; version: int): bool =
  version >= e.since

type WpColorRepresentationSurfaceV1Error* {.size: sizeof(uint32).} = enum
  error_alpha_mode = 1
  error_coefficients = 2
  error_pixel_format = 3
  error_inert = 4
func since*(e: WpColorRepresentationSurfaceV1Error): int =
  case e
  of error_alpha_mode: 1
  of error_coefficients: 1
  of error_pixel_format: 1
  of error_inert: 1
proc isValid*(e: WpColorRepresentationSurfaceV1Error; version: int): bool =
  version >= e.since

type WpColorRepresentationSurfaceV1AlphaMode* {.size: sizeof(uint32).} = enum
  alpha_mode_premultiplied_electrical = 0
  alpha_mode_premultiplied_optical = 1
  alpha_mode_straight = 2
func since*(e: WpColorRepresentationSurfaceV1AlphaMode): int =
  case e
  of alpha_mode_premultiplied_electrical: 1
  of alpha_mode_premultiplied_optical: 1
  of alpha_mode_straight: 1
proc isValid*(e: WpColorRepresentationSurfaceV1AlphaMode; version: int): bool =
  version >= e.since

type WpColorRepresentationSurfaceV1Coefficients* {.size: sizeof(uint32).} = enum
  coefficients_identity = 1
  coefficients_bt709 = 2
  coefficients_fcc = 3
  coefficients_bt601 = 4
  coefficients_smpte240 = 5
  coefficients_bt2020 = 6
  coefficients_bt2020_cl = 7
  coefficients_ictcp = 8
func since*(e: WpColorRepresentationSurfaceV1Coefficients): int =
  case e
  of coefficients_identity: 1
  of coefficients_bt709: 1
  of coefficients_fcc: 1
  of coefficients_bt601: 1
  of coefficients_smpte240: 1
  of coefficients_bt2020: 1
  of coefficients_bt2020_cl: 1
  of coefficients_ictcp: 1
proc isValid*(e: WpColorRepresentationSurfaceV1Coefficients; version: int): bool =
  version >= e.since

type WpColorRepresentationSurfaceV1Range* {.size: sizeof(uint32).} = enum
  range_full = 1
  range_limited = 2
func since*(e: WpColorRepresentationSurfaceV1Range): int =
  case e
  of range_full: 1
  of range_limited: 1
proc isValid*(e: WpColorRepresentationSurfaceV1Range; version: int): bool =
  version >= e.since

type WpColorRepresentationSurfaceV1ChromaLocation* {.size: sizeof(uint32).} = enum
  chroma_location_type_0 = 1
  chroma_location_type_1 = 2
  chroma_location_type_2 = 3
  chroma_location_type_3 = 4
  chroma_location_type_4 = 5
  chroma_location_type_5 = 6
func since*(e: WpColorRepresentationSurfaceV1ChromaLocation): int =
  case e
  of chroma_location_type_0: 1
  of chroma_location_type_1: 1
  of chroma_location_type_2: 1
  of chroma_location_type_3: 1
  of chroma_location_type_4: 1
  of chroma_location_type_5: 1
proc isValid*(e: WpColorRepresentationSurfaceV1ChromaLocation; version: int): bool =
  version >= e.since

type WpColorRepresentationManagerV1Event* {.size: sizeof(uint32).} = enum
  WpColorRepresentationManagerV1Event_supported_alpha_mode
  WpColorRepresentationManagerV1Event_supported_coefficients_and_ranges
  WpColorRepresentationManagerV1Event_done
proc since*(e: WpColorRepresentationManagerV1Event): int =
  case e
  of WpColorRepresentationManagerV1Event_supported_alpha_mode: 1
  of WpColorRepresentationManagerV1Event_supported_coefficients_and_ranges: 1
  of WpColorRepresentationManagerV1Event_done: 1

type WpColorRepresentationManagerV1Request* {.size: sizeof(uint32).} = enum
  WpColorRepresentationManagerV1Request_destroy
  WpColorRepresentationManagerV1Request_get_surface
proc since*(e: WpColorRepresentationManagerV1Request): int =
  case e
  of WpColorRepresentationManagerV1Request_destroy: 1
  of WpColorRepresentationManagerV1Request_get_surface: 1

type WpColorRepresentationSurfaceV1Request* {.size: sizeof(uint32).} = enum
  WpColorRepresentationSurfaceV1Request_destroy
  WpColorRepresentationSurfaceV1Request_set_alpha_mode
  WpColorRepresentationSurfaceV1Request_set_coefficients_and_range
  WpColorRepresentationSurfaceV1Request_set_chroma_location
proc since*(e: WpColorRepresentationSurfaceV1Request): int =
  case e
  of WpColorRepresentationSurfaceV1Request_destroy: 1
  of WpColorRepresentationSurfaceV1Request_set_alpha_mode: 1
  of WpColorRepresentationSurfaceV1Request_set_coefficients_and_range: 1
  of WpColorRepresentationSurfaceV1Request_set_chroma_location: 1

colorRepresentationV1_types = [
  nil,
  nil,
  addr wp_color_representation_surface_v1_interface,
  addr wl_surface_interface,
]


