# Generated by wayland-nim-scanner 1.23.1
{.warning[UnusedImport]:off.}
import wayland/native/server
import wayland/native/common
import code
export code

## The color_representation_v1 SERVER protocol
## ###########################################
## 
## Interfaces
## ==========
## 
## * wp_color_representation_manager_v1
## * wp_color_representation_surface_v1
## 
## Copyright
## =========
## 
## Copyright 2022 Simon Ser
## Copyright 2022 Red Hat, Inc.
## Copyright 2022 Collabora, Ltd.
## Copyright 2022-2025 Red Hat, Inc.
## 
## Permission is hereby granted, free of charge, to any person obtaining a
## copy of this software and associated documentation files (the "Software"),
## to deal in the Software without restriction, including without limitation
## the rights to use, copy, modify, merge, publish, distribute, sublicense,
## and/or sell copies of the Software, and to permit persons to whom the
## Software is furnished to do so, subject to the following conditions:
## 
## The above copyright notice and this permission notice (including the next
## paragraph) shall be included in all copies or substantial portions of the
## Software.
## 
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
## IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
## FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
## THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
## LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
## FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
## DEALINGS IN THE SOFTWARE.
## 

type WpColorRepresentationManagerV1Interface* = object
  destroy*: proc(
    client: ptr Client;
    resource: ptr Resource;
  ) {.nimcall.}
  getSurface*: proc(
    client: ptr Client;
    resource: ptr Resource;
    id: uint32;
    surface: ptr Resource;
  ) {.nimcall.}

proc wpColorRepresentationManagerV1SendSupportedAlphaMode*(resource: ptr Resource; alphaMode: uint32) {.inline, exportc: "wp_color_representation_manager_v1_send_supported_alpha_mode".} =
  ## Sends an supported_alpha_mode event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  ## * *alpha_mode*: supported alpha mode
  resource.post_event(WpColorRepresentationManagerV1Event_supported_alpha_mode.ord, alphaMode)

proc wpColorRepresentationManagerV1SendSupportedCoefficientsAndRanges*(resource: ptr Resource; coefficients: uint32; range: uint32) {.inline, exportc: "wp_color_representation_manager_v1_send_supported_coefficients_and_ranges".} =
  ## Sends an supported_coefficients_and_ranges event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  ## * *coefficients*: supported matrix coefficients
  ## * *range*: full range flag
  resource.post_event(WpColorRepresentationManagerV1Event_supported_coefficients_and_ranges.ord, coefficients, range)

proc wpColorRepresentationManagerV1SendDone*(resource: ptr Resource) {.inline, exportc: "wp_color_representation_manager_v1_send_done".} =
  ## Sends an done event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(WpColorRepresentationManagerV1Event_done.ord)

type WpColorRepresentationSurfaceV1Interface* = object
  destroy*: proc(
    client: ptr Client;
    resource: ptr Resource;
  ) {.nimcall.}
  setAlphaMode*: proc(
    client: ptr Client;
    resource: ptr Resource;
    alphaMode: uint32;
  ) {.nimcall.}
  setCoefficientsAndRange*: proc(
    client: ptr Client;
    resource: ptr Resource;
    coefficients: uint32;
    range: uint32;
  ) {.nimcall.}
  setChromaLocation*: proc(
    client: ptr Client;
    resource: ptr Resource;
    chromaLocation: uint32;
  ) {.nimcall.}

