# Generated by wayland-nim-scanner 1.23.1
{.warning[UnusedImport]:off.}
import wayland/native/common
import wayland/protocols/wayland/code as wayland_code

var extTransientSeatV1_types: array[2, ptr Interface]
type ExtTransientSeatManagerV1* = object
type ExtTransientSeatV1* = object

let
  ext_transient_seat_manager_v1_requests {.exportc.} = [
    Message(name: "create", signature: "n", types: addr ext_transient_seat_v1_types[1]),
    Message(name: "destroy", signature: "", types: addr ext_transient_seat_v1_types[0]),
  ]

  ext_transient_seat_manager_v1_interface* {.exportc.} = Interface(
    name: "ext_transient_seat_manager_v1",
    version: 1,
    method_count: 2,
    methods: addr ext_transient_seat_manager_v1_requests[0],
  )

  ext_transient_seat_v1_requests {.exportc.} = [
    Message(name: "destroy", signature: "", types: addr ext_transient_seat_v1_types[0]),
  ]

  ext_transient_seat_v1_events {.exportc.} = [
    Message(name: "ready", signature: "u", types: addr ext_transient_seat_v1_types[0]),
    Message(name: "denied", signature: "", types: addr ext_transient_seat_v1_types[0]),
  ]

  ext_transient_seat_v1_interface* {.exportc.} = Interface(
    name: "ext_transient_seat_v1",
    version: 1,
    method_count: 1,
    methods: addr ext_transient_seat_v1_requests[0],
    event_count: 2,
    events: addr ext_transient_seat_v1_events[0],
  )


type ExtTransientSeatManagerV1Request* {.size: sizeof(uint32).} = enum
  ExtTransientSeatManagerV1Request_create
  ExtTransientSeatManagerV1Request_destroy
proc since*(e: ExtTransientSeatManagerV1Request): int =
  case e
  of ExtTransientSeatManagerV1Request_create: 1
  of ExtTransientSeatManagerV1Request_destroy: 1

type ExtTransientSeatV1Event* {.size: sizeof(uint32).} = enum
  ExtTransientSeatV1Event_ready
  ExtTransientSeatV1Event_denied
proc since*(e: ExtTransientSeatV1Event): int =
  case e
  of ExtTransientSeatV1Event_ready: 1
  of ExtTransientSeatV1Event_denied: 1

type ExtTransientSeatV1Request* {.size: sizeof(uint32).} = enum
  ExtTransientSeatV1Request_destroy
proc since*(e: ExtTransientSeatV1Request): int =
  case e
  of ExtTransientSeatV1Request_destroy: 1

extTransientSeatV1_types = [
  nil,
  addr ext_transient_seat_v1_interface,
]


