# Generated by wayland-nim-scanner 1.23.1
{.warning[UnusedImport]:off.}
import wayland/native/server
import wayland/native/common
import code
export code

## The xdg_activation_v1 SERVER protocol
## #####################################
## 
## Interfaces
## ==========
## 
## * xdg_activation_v1
## * xdg_activation_token_v1
## 
## Copyright
## =========
## 
## Copyright © 2020 Aleix Pol Gonzalez 

type XdgActivationV1Interface* = object
  destroy*: proc(
    client: ptr Client;
    resource: ptr Resource;
  ) {.nimcall.}
  getActivationToken*: proc(
    client: ptr Client;
    resource: ptr Resource;
    id: uint32;
  ) {.nimcall.}
  activate*: proc(
    client: ptr Client;
    resource: ptr Resource;
    token: cstring;
    surface: ptr Resource;
  ) {.nimcall.}

type XdgActivationTokenV1Interface* = object
  setSerial*: proc(
    client: ptr Client;
    resource: ptr Resource;
    serial: uint32;
    seat: ptr Resource;
  ) {.nimcall.}
  setAppId*: proc(
    client: ptr Client;
    resource: ptr Resource;
    appId: cstring;
  ) {.nimcall.}
  setSurface*: proc(
    client: ptr Client;
    resource: ptr Resource;
    surface: ptr Resource;
  ) {.nimcall.}
  commit*: proc(
    client: ptr Client;
    resource: ptr Resource;
  ) {.nimcall.}
  destroy*: proc(
    client: ptr Client;
    resource: ptr Resource;
  ) {.nimcall.}

proc xdgActivationTokenV1SendDone*(resource: ptr Resource; token: cstring) {.inline, exportc: "xdg_activation_token_v1_send_done".} =
  ## Sends an done event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  ## * *token*: the exported activation token
  resource.post_event(XdgActivationTokenV1Event_done.ord, token)

