# Generated by wayland-nim-scanner 1.23.1
{.warning[UnusedImport]:off.}
import wayland/native/common
import wayland/protocols/wayland/code as wayland_code

var tearingControlV1_types: array[3, ptr Interface]
type WpTearingControlManagerV1* = object
type WpTearingControlV1* = object

let
  wp_tearing_control_manager_v1_requests {.exportc.} = [
    Message(name: "destroy", signature: "", types: addr tearing_control_v1_types[0]),
    Message(name: "get_tearing_control", signature: "no", types: addr tearing_control_v1_types[1]),
  ]

  wp_tearing_control_manager_v1_interface* {.exportc.} = Interface(
    name: "wp_tearing_control_manager_v1",
    version: 1,
    method_count: 2,
    methods: addr wp_tearing_control_manager_v1_requests[0],
  )

  wp_tearing_control_v1_requests {.exportc.} = [
    Message(name: "set_presentation_hint", signature: "u", types: addr tearing_control_v1_types[0]),
    Message(name: "destroy", signature: "", types: addr tearing_control_v1_types[0]),
  ]

  wp_tearing_control_v1_interface* {.exportc.} = Interface(
    name: "wp_tearing_control_v1",
    version: 1,
    method_count: 2,
    methods: addr wp_tearing_control_v1_requests[0],
  )


type WpTearingControlManagerV1Error* {.size: sizeof(uint32).} = enum
  error_tearing_control_exists = 0
func since*(e: WpTearingControlManagerV1Error): int =
  case e
  of error_tearing_control_exists: 1
proc isValid*(e: WpTearingControlManagerV1Error; version: int): bool =
  version >= e.since

type WpTearingControlV1PresentationHint* {.size: sizeof(uint32).} = enum
  presentation_hint_vsync = 0
  presentation_hint_async = 1
func since*(e: WpTearingControlV1PresentationHint): int =
  case e
  of presentation_hint_vsync: 1
  of presentation_hint_async: 1
proc isValid*(e: WpTearingControlV1PresentationHint; version: int): bool =
  version >= e.since

type WpTearingControlManagerV1Request* {.size: sizeof(uint32).} = enum
  WpTearingControlManagerV1Request_destroy
  WpTearingControlManagerV1Request_get_tearing_control
proc since*(e: WpTearingControlManagerV1Request): int =
  case e
  of WpTearingControlManagerV1Request_destroy: 1
  of WpTearingControlManagerV1Request_get_tearing_control: 1

type WpTearingControlV1Request* {.size: sizeof(uint32).} = enum
  WpTearingControlV1Request_set_presentation_hint
  WpTearingControlV1Request_destroy
proc since*(e: WpTearingControlV1Request): int =
  case e
  of WpTearingControlV1Request_set_presentation_hint: 1
  of WpTearingControlV1Request_destroy: 1

tearingControlV1_types = [
  nil,
  addr wp_tearing_control_v1_interface,
  addr wl_surface_interface,
]


