# Generated by wayland-nim-scanner 1.23.1
{.warning[UnusedImport]:off.}
import wayland/native/common
import wayland/protocols/wayland/code as wayland_code

var xdgShell_types: array[26, ptr Interface]
type XdgPopup* = object
type XdgPositioner* = object
type XdgSurface* = object
type XdgToplevel* = object
type XdgWmBase* = object

let
  xdg_wm_base_requests {.exportc.} = [
    Message(name: "destroy", signature: "", types: addr xdg_shell_types[0]),
    Message(name: "create_positioner", signature: "n", types: addr xdg_shell_types[4]),
    Message(name: "get_xdg_surface", signature: "no", types: addr xdg_shell_types[5]),
    Message(name: "pong", signature: "u", types: addr xdg_shell_types[0]),
  ]

  xdg_wm_base_events {.exportc.} = [
    Message(name: "ping", signature: "u", types: addr xdg_shell_types[0]),
  ]

  xdg_wm_base_interface* {.exportc.} = Interface(
    name: "xdg_wm_base",
    version: 7,
    method_count: 4,
    methods: addr xdg_wm_base_requests[0],
    event_count: 1,
    events: addr xdg_wm_base_events[0],
  )

  xdg_positioner_requests {.exportc.} = [
    Message(name: "destroy", signature: "", types: addr xdg_shell_types[0]),
    Message(name: "set_size", signature: "ii", types: addr xdg_shell_types[0]),
    Message(name: "set_anchor_rect", signature: "iiii", types: addr xdg_shell_types[0]),
    Message(name: "set_anchor", signature: "u", types: addr xdg_shell_types[0]),
    Message(name: "set_gravity", signature: "u", types: addr xdg_shell_types[0]),
    Message(name: "set_constraint_adjustment", signature: "u", types: addr xdg_shell_types[0]),
    Message(name: "set_offset", signature: "ii", types: addr xdg_shell_types[0]),
    Message(name: "set_reactive", signature: "3", types: addr xdg_shell_types[0]),
    Message(name: "set_parent_size", signature: "3ii", types: addr xdg_shell_types[0]),
    Message(name: "set_parent_configure", signature: "3u", types: addr xdg_shell_types[0]),
  ]

  xdg_positioner_interface* {.exportc.} = Interface(
    name: "xdg_positioner",
    version: 7,
    method_count: 10,
    methods: addr xdg_positioner_requests[0],
  )

  xdg_surface_requests {.exportc.} = [
    Message(name: "destroy", signature: "", types: addr xdg_shell_types[0]),
    Message(name: "get_toplevel", signature: "n", types: addr xdg_shell_types[7]),
    Message(name: "get_popup", signature: "n?oo", types: addr xdg_shell_types[8]),
    Message(name: "set_window_geometry", signature: "iiii", types: addr xdg_shell_types[0]),
    Message(name: "ack_configure", signature: "u", types: addr xdg_shell_types[0]),
  ]

  xdg_surface_events {.exportc.} = [
    Message(name: "configure", signature: "u", types: addr xdg_shell_types[0]),
  ]

  xdg_surface_interface* {.exportc.} = Interface(
    name: "xdg_surface",
    version: 7,
    method_count: 5,
    methods: addr xdg_surface_requests[0],
    event_count: 1,
    events: addr xdg_surface_events[0],
  )

  xdg_toplevel_requests {.exportc.} = [
    Message(name: "destroy", signature: "", types: addr xdg_shell_types[0]),
    Message(name: "set_parent", signature: "?o", types: addr xdg_shell_types[11]),
    Message(name: "set_title", signature: "s", types: addr xdg_shell_types[0]),
    Message(name: "set_app_id", signature: "s", types: addr xdg_shell_types[0]),
    Message(name: "show_window_menu", signature: "ouii", types: addr xdg_shell_types[12]),
    Message(name: "move", signature: "ou", types: addr xdg_shell_types[16]),
    Message(name: "resize", signature: "ouu", types: addr xdg_shell_types[18]),
    Message(name: "set_max_size", signature: "ii", types: addr xdg_shell_types[0]),
    Message(name: "set_min_size", signature: "ii", types: addr xdg_shell_types[0]),
    Message(name: "set_maximized", signature: "", types: addr xdg_shell_types[0]),
    Message(name: "unset_maximized", signature: "", types: addr xdg_shell_types[0]),
    Message(name: "set_fullscreen", signature: "?o", types: addr xdg_shell_types[21]),
    Message(name: "unset_fullscreen", signature: "", types: addr xdg_shell_types[0]),
    Message(name: "set_minimized", signature: "", types: addr xdg_shell_types[0]),
  ]

  xdg_toplevel_events {.exportc.} = [
    Message(name: "configure", signature: "iia", types: addr xdg_shell_types[0]),
    Message(name: "close", signature: "", types: addr xdg_shell_types[0]),
    Message(name: "configure_bounds", signature: "4ii", types: addr xdg_shell_types[0]),
    Message(name: "wm_capabilities", signature: "5a", types: addr xdg_shell_types[0]),
  ]

  xdg_toplevel_interface* {.exportc.} = Interface(
    name: "xdg_toplevel",
    version: 7,
    method_count: 14,
    methods: addr xdg_toplevel_requests[0],
    event_count: 4,
    events: addr xdg_toplevel_events[0],
  )

  xdg_popup_requests {.exportc.} = [
    Message(name: "destroy", signature: "", types: addr xdg_shell_types[0]),
    Message(name: "grab", signature: "ou", types: addr xdg_shell_types[22]),
    Message(name: "reposition", signature: "3ou", types: addr xdg_shell_types[24]),
  ]

  xdg_popup_events {.exportc.} = [
    Message(name: "configure", signature: "iiii", types: addr xdg_shell_types[0]),
    Message(name: "popup_done", signature: "", types: addr xdg_shell_types[0]),
    Message(name: "repositioned", signature: "3u", types: addr xdg_shell_types[0]),
  ]

  xdg_popup_interface* {.exportc.} = Interface(
    name: "xdg_popup",
    version: 7,
    method_count: 3,
    methods: addr xdg_popup_requests[0],
    event_count: 3,
    events: addr xdg_popup_events[0],
  )


type XdgWmBaseError* {.size: sizeof(uint32).} = enum
  error_role = 0
  error_defunct_surfaces = 1
  error_not_the_topmost_popup = 2
  error_invalid_popup_parent = 3
  error_invalid_surface_state = 4
  error_invalid_positioner = 5
  error_unresponsive = 6
func since*(e: XdgWmBaseError): int =
  case e
  of error_role: 1
  of error_defunct_surfaces: 1
  of error_not_the_topmost_popup: 1
  of error_invalid_popup_parent: 1
  of error_invalid_surface_state: 1
  of error_invalid_positioner: 1
  of error_unresponsive: 1
proc isValid*(e: XdgWmBaseError; version: int): bool =
  version >= e.since

type XdgPositionerError* {.size: sizeof(uint32).} = enum
  error_invalid_input = 0
func since*(e: XdgPositionerError): int =
  case e
  of error_invalid_input: 1
proc isValid*(e: XdgPositionerError; version: int): bool =
  version >= e.since

type XdgPositionerAnchor* {.size: sizeof(uint32).} = enum
  anchor_none = 0
  anchor_top = 1
  anchor_bottom = 2
  anchor_left = 3
  anchor_right = 4
  anchor_top_left = 5
  anchor_bottom_left = 6
  anchor_top_right = 7
  anchor_bottom_right = 8
func since*(e: XdgPositionerAnchor): int =
  case e
  of anchor_none: 1
  of anchor_top: 1
  of anchor_bottom: 1
  of anchor_left: 1
  of anchor_right: 1
  of anchor_top_left: 1
  of anchor_bottom_left: 1
  of anchor_top_right: 1
  of anchor_bottom_right: 1
proc isValid*(e: XdgPositionerAnchor; version: int): bool =
  version >= e.since

type XdgPositionerGravity* {.size: sizeof(uint32).} = enum
  gravity_none = 0
  gravity_top = 1
  gravity_bottom = 2
  gravity_left = 3
  gravity_right = 4
  gravity_top_left = 5
  gravity_bottom_left = 6
  gravity_top_right = 7
  gravity_bottom_right = 8
func since*(e: XdgPositionerGravity): int =
  case e
  of gravity_none: 1
  of gravity_top: 1
  of gravity_bottom: 1
  of gravity_left: 1
  of gravity_right: 1
  of gravity_top_left: 1
  of gravity_bottom_left: 1
  of gravity_top_right: 1
  of gravity_bottom_right: 1
proc isValid*(e: XdgPositionerGravity; version: int): bool =
  version >= e.since

type XdgPositionerConstraintAdjustment* {.size: sizeof(uint32).} = enum
  constraint_adjustment_none = 0
  constraint_adjustment_slide_x = 1
  constraint_adjustment_slide_y = 2
  constraint_adjustment_flip_x = 4
  constraint_adjustment_flip_y = 8
  constraint_adjustment_resize_x = 16
  constraint_adjustment_resize_y = 32
func since*(e: XdgPositionerConstraintAdjustment): int =
  case e
  of constraint_adjustment_none: 1
  of constraint_adjustment_slide_x: 1
  of constraint_adjustment_slide_y: 1
  of constraint_adjustment_flip_x: 1
  of constraint_adjustment_flip_y: 1
  of constraint_adjustment_resize_x: 1
  of constraint_adjustment_resize_y: 1
proc isValid*(e: XdgPositionerConstraintAdjustment; version: int): bool =
  version >= e.since

type XdgSurfaceError* {.size: sizeof(uint32).} = enum
  error_not_constructed = 1
  error_already_constructed = 2
  error_unconfigured_buffer = 3
  error_invalid_serial = 4
  error_invalid_size = 5
  error_defunct_role_object = 6
func since*(e: XdgSurfaceError): int =
  case e
  of error_not_constructed: 1
  of error_already_constructed: 1
  of error_unconfigured_buffer: 1
  of error_invalid_serial: 1
  of error_invalid_size: 1
  of error_defunct_role_object: 1
proc isValid*(e: XdgSurfaceError; version: int): bool =
  version >= e.since

type XdgToplevelError* {.size: sizeof(uint32).} = enum
  error_invalid_resize_edge = 0
  error_invalid_parent = 1
  error_invalid_size = 2
func since*(e: XdgToplevelError): int =
  case e
  of error_invalid_resize_edge: 1
  of error_invalid_parent: 1
  of error_invalid_size: 1
proc isValid*(e: XdgToplevelError; version: int): bool =
  version >= e.since

type XdgToplevelResizeEdge* {.size: sizeof(uint32).} = enum
  resize_edge_none = 0
  resize_edge_top = 1
  resize_edge_bottom = 2
  resize_edge_left = 4
  resize_edge_top_left = 5
  resize_edge_bottom_left = 6
  resize_edge_right = 8
  resize_edge_top_right = 9
  resize_edge_bottom_right = 10
func since*(e: XdgToplevelResizeEdge): int =
  case e
  of resize_edge_none: 1
  of resize_edge_top: 1
  of resize_edge_bottom: 1
  of resize_edge_left: 1
  of resize_edge_top_left: 1
  of resize_edge_bottom_left: 1
  of resize_edge_right: 1
  of resize_edge_top_right: 1
  of resize_edge_bottom_right: 1
proc isValid*(e: XdgToplevelResizeEdge; version: int): bool =
  version >= e.since

type XdgToplevelState* {.size: sizeof(uint32).} = enum
  state_maximized = 1
  state_fullscreen = 2
  state_resizing = 3
  state_activated = 4
  state_tiled_left = 5
  state_tiled_right = 6
  state_tiled_top = 7
  state_tiled_bottom = 8
  state_suspended = 9
  state_constrained_left = 10
  state_constrained_right = 11
  state_constrained_top = 12
  state_constrained_bottom = 13
func since*(e: XdgToplevelState): int =
  case e
  of state_maximized: 1
  of state_fullscreen: 1
  of state_resizing: 1
  of state_activated: 1
  of state_tiled_left: 2
  of state_tiled_right: 2
  of state_tiled_top: 2
  of state_tiled_bottom: 2
  of state_suspended: 6
  of state_constrained_left: 7
  of state_constrained_right: 7
  of state_constrained_top: 7
  of state_constrained_bottom: 7
proc isValid*(e: XdgToplevelState; version: int): bool =
  version >= e.since

type XdgToplevelWmCapabilities* {.size: sizeof(uint32).} = enum
  wm_capabilities_window_menu = 1
  wm_capabilities_maximize = 2
  wm_capabilities_fullscreen = 3
  wm_capabilities_minimize = 4
func since*(e: XdgToplevelWmCapabilities): int =
  case e
  of wm_capabilities_window_menu: 5
  of wm_capabilities_maximize: 5
  of wm_capabilities_fullscreen: 5
  of wm_capabilities_minimize: 5
proc isValid*(e: XdgToplevelWmCapabilities; version: int): bool =
  version >= e.since

type XdgPopupError* {.size: sizeof(uint32).} = enum
  error_invalid_grab = 0
func since*(e: XdgPopupError): int =
  case e
  of error_invalid_grab: 1
proc isValid*(e: XdgPopupError; version: int): bool =
  version >= e.since

type XdgWmBaseEvent* {.size: sizeof(uint32).} = enum
  XdgWmBaseEvent_ping
proc since*(e: XdgWmBaseEvent): int =
  case e
  of XdgWmBaseEvent_ping: 1

type XdgWmBaseRequest* {.size: sizeof(uint32).} = enum
  XdgWmBaseRequest_destroy
  XdgWmBaseRequest_create_positioner
  XdgWmBaseRequest_get_xdg_surface
  XdgWmBaseRequest_pong
proc since*(e: XdgWmBaseRequest): int =
  case e
  of XdgWmBaseRequest_destroy: 1
  of XdgWmBaseRequest_create_positioner: 1
  of XdgWmBaseRequest_get_xdg_surface: 1
  of XdgWmBaseRequest_pong: 1

type XdgPositionerRequest* {.size: sizeof(uint32).} = enum
  XdgPositionerRequest_destroy
  XdgPositionerRequest_set_size
  XdgPositionerRequest_set_anchor_rect
  XdgPositionerRequest_set_anchor
  XdgPositionerRequest_set_gravity
  XdgPositionerRequest_set_constraint_adjustment
  XdgPositionerRequest_set_offset
  XdgPositionerRequest_set_reactive
  XdgPositionerRequest_set_parent_size
  XdgPositionerRequest_set_parent_configure
proc since*(e: XdgPositionerRequest): int =
  case e
  of XdgPositionerRequest_destroy: 1
  of XdgPositionerRequest_set_size: 1
  of XdgPositionerRequest_set_anchor_rect: 1
  of XdgPositionerRequest_set_anchor: 1
  of XdgPositionerRequest_set_gravity: 1
  of XdgPositionerRequest_set_constraint_adjustment: 1
  of XdgPositionerRequest_set_offset: 1
  of XdgPositionerRequest_set_reactive: 3
  of XdgPositionerRequest_set_parent_size: 3
  of XdgPositionerRequest_set_parent_configure: 3

type XdgSurfaceEvent* {.size: sizeof(uint32).} = enum
  XdgSurfaceEvent_configure
proc since*(e: XdgSurfaceEvent): int =
  case e
  of XdgSurfaceEvent_configure: 1

type XdgSurfaceRequest* {.size: sizeof(uint32).} = enum
  XdgSurfaceRequest_destroy
  XdgSurfaceRequest_get_toplevel
  XdgSurfaceRequest_get_popup
  XdgSurfaceRequest_set_window_geometry
  XdgSurfaceRequest_ack_configure
proc since*(e: XdgSurfaceRequest): int =
  case e
  of XdgSurfaceRequest_destroy: 1
  of XdgSurfaceRequest_get_toplevel: 1
  of XdgSurfaceRequest_get_popup: 1
  of XdgSurfaceRequest_set_window_geometry: 1
  of XdgSurfaceRequest_ack_configure: 1

type XdgToplevelEvent* {.size: sizeof(uint32).} = enum
  XdgToplevelEvent_configure
  XdgToplevelEvent_close
  XdgToplevelEvent_configure_bounds
  XdgToplevelEvent_wm_capabilities
proc since*(e: XdgToplevelEvent): int =
  case e
  of XdgToplevelEvent_configure: 1
  of XdgToplevelEvent_close: 1
  of XdgToplevelEvent_configure_bounds: 4
  of XdgToplevelEvent_wm_capabilities: 5

type XdgToplevelRequest* {.size: sizeof(uint32).} = enum
  XdgToplevelRequest_destroy
  XdgToplevelRequest_set_parent
  XdgToplevelRequest_set_title
  XdgToplevelRequest_set_app_id
  XdgToplevelRequest_show_window_menu
  XdgToplevelRequest_move
  XdgToplevelRequest_resize
  XdgToplevelRequest_set_max_size
  XdgToplevelRequest_set_min_size
  XdgToplevelRequest_set_maximized
  XdgToplevelRequest_unset_maximized
  XdgToplevelRequest_set_fullscreen
  XdgToplevelRequest_unset_fullscreen
  XdgToplevelRequest_set_minimized
proc since*(e: XdgToplevelRequest): int =
  case e
  of XdgToplevelRequest_destroy: 1
  of XdgToplevelRequest_set_parent: 1
  of XdgToplevelRequest_set_title: 1
  of XdgToplevelRequest_set_app_id: 1
  of XdgToplevelRequest_show_window_menu: 1
  of XdgToplevelRequest_move: 1
  of XdgToplevelRequest_resize: 1
  of XdgToplevelRequest_set_max_size: 1
  of XdgToplevelRequest_set_min_size: 1
  of XdgToplevelRequest_set_maximized: 1
  of XdgToplevelRequest_unset_maximized: 1
  of XdgToplevelRequest_set_fullscreen: 1
  of XdgToplevelRequest_unset_fullscreen: 1
  of XdgToplevelRequest_set_minimized: 1

type XdgPopupEvent* {.size: sizeof(uint32).} = enum
  XdgPopupEvent_configure
  XdgPopupEvent_popup_done
  XdgPopupEvent_repositioned
proc since*(e: XdgPopupEvent): int =
  case e
  of XdgPopupEvent_configure: 1
  of XdgPopupEvent_popup_done: 1
  of XdgPopupEvent_repositioned: 3

type XdgPopupRequest* {.size: sizeof(uint32).} = enum
  XdgPopupRequest_destroy
  XdgPopupRequest_grab
  XdgPopupRequest_reposition
proc since*(e: XdgPopupRequest): int =
  case e
  of XdgPopupRequest_destroy: 1
  of XdgPopupRequest_grab: 1
  of XdgPopupRequest_reposition: 3

xdgShell_types = [
  nil,
  nil,
  nil,
  nil,
  addr xdg_positioner_interface,
  addr xdg_surface_interface,
  addr wl_surface_interface,
  addr xdg_toplevel_interface,
  addr xdg_popup_interface,
  addr xdg_surface_interface,
  addr xdg_positioner_interface,
  addr xdg_toplevel_interface,
  addr wl_seat_interface,
  nil,
  nil,
  nil,
  addr wl_seat_interface,
  nil,
  addr wl_seat_interface,
  nil,
  nil,
  addr wl_output_interface,
  addr wl_seat_interface,
  nil,
  addr xdg_positioner_interface,
  nil,
]


