# Generated by wayland-nim-scanner 1.23.1
{.warning[UnusedImport]:off.}
import wayland/native/common
import wayland/protocols/wayland/code as wayland_code

var xwaylandShellV1_types: array[4, ptr Interface]
type XwaylandShellV1* = object
type XwaylandSurfaceV1* = object

let
  xwayland_shell_v1_requests {.exportc.} = [
    Message(name: "destroy", signature: "", types: addr xwayland_shell_v1_types[0]),
    Message(name: "get_xwayland_surface", signature: "no", types: addr xwayland_shell_v1_types[2]),
  ]

  xwayland_shell_v1_interface* {.exportc.} = Interface(
    name: "xwayland_shell_v1",
    version: 1,
    method_count: 2,
    methods: addr xwayland_shell_v1_requests[0],
  )

  xwayland_surface_v1_requests {.exportc.} = [
    Message(name: "set_serial", signature: "uu", types: addr xwayland_shell_v1_types[0]),
    Message(name: "destroy", signature: "", types: addr xwayland_shell_v1_types[0]),
  ]

  xwayland_surface_v1_interface* {.exportc.} = Interface(
    name: "xwayland_surface_v1",
    version: 1,
    method_count: 2,
    methods: addr xwayland_surface_v1_requests[0],
  )


type XwaylandShellV1Error* {.size: sizeof(uint32).} = enum
  error_role = 0
func since*(e: XwaylandShellV1Error): int =
  case e
  of error_role: 1
proc isValid*(e: XwaylandShellV1Error; version: int): bool =
  version >= e.since

type XwaylandSurfaceV1Error* {.size: sizeof(uint32).} = enum
  error_already_associated = 0
  error_invalid_serial = 1
func since*(e: XwaylandSurfaceV1Error): int =
  case e
  of error_already_associated: 1
  of error_invalid_serial: 1
proc isValid*(e: XwaylandSurfaceV1Error; version: int): bool =
  version >= e.since

type XwaylandShellV1Request* {.size: sizeof(uint32).} = enum
  XwaylandShellV1Request_destroy
  XwaylandShellV1Request_get_xwayland_surface
proc since*(e: XwaylandShellV1Request): int =
  case e
  of XwaylandShellV1Request_destroy: 1
  of XwaylandShellV1Request_get_xwayland_surface: 1

type XwaylandSurfaceV1Request* {.size: sizeof(uint32).} = enum
  XwaylandSurfaceV1Request_set_serial
  XwaylandSurfaceV1Request_destroy
proc since*(e: XwaylandSurfaceV1Request): int =
  case e
  of XwaylandSurfaceV1Request_set_serial: 1
  of XwaylandSurfaceV1Request_destroy: 1

xwaylandShellV1_types = [
  nil,
  nil,
  addr xwayland_surface_v1_interface,
  addr wl_surface_interface,
]


