# Generated by wayland-nim-scanner 1.23.1
{.warning[UnusedImport]:off.}
import wayland/native/common
import wayland/protocols/wayland/code as wayland_code

var extWorkspaceV1_types: array[8, ptr Interface]
type ExtWorkspaceGroupHandleV1* = object
type ExtWorkspaceHandleV1* = object
type ExtWorkspaceManagerV1* = object

let
  ext_workspace_manager_v1_requests {.exportc.} = [
    Message(name: "commit", signature: "", types: addr ext_workspace_v1_types[0]),
    Message(name: "stop", signature: "", types: addr ext_workspace_v1_types[0]),
  ]

  ext_workspace_manager_v1_events {.exportc.} = [
    Message(name: "workspace_group", signature: "n", types: addr ext_workspace_v1_types[1]),
    Message(name: "workspace", signature: "n", types: addr ext_workspace_v1_types[2]),
    Message(name: "done", signature: "", types: addr ext_workspace_v1_types[0]),
    Message(name: "finished", signature: "", types: addr ext_workspace_v1_types[0]),
  ]

  ext_workspace_manager_v1_interface* {.exportc.} = Interface(
    name: "ext_workspace_manager_v1",
    version: 1,
    method_count: 2,
    methods: addr ext_workspace_manager_v1_requests[0],
    event_count: 4,
    events: addr ext_workspace_manager_v1_events[0],
  )

  ext_workspace_group_handle_v1_requests {.exportc.} = [
    Message(name: "create_workspace", signature: "s", types: addr ext_workspace_v1_types[0]),
    Message(name: "destroy", signature: "", types: addr ext_workspace_v1_types[0]),
  ]

  ext_workspace_group_handle_v1_events {.exportc.} = [
    Message(name: "capabilities", signature: "u", types: addr ext_workspace_v1_types[0]),
    Message(name: "output_enter", signature: "o", types: addr ext_workspace_v1_types[3]),
    Message(name: "output_leave", signature: "o", types: addr ext_workspace_v1_types[4]),
    Message(name: "workspace_enter", signature: "o", types: addr ext_workspace_v1_types[5]),
    Message(name: "workspace_leave", signature: "o", types: addr ext_workspace_v1_types[6]),
    Message(name: "removed", signature: "", types: addr ext_workspace_v1_types[0]),
  ]

  ext_workspace_group_handle_v1_interface* {.exportc.} = Interface(
    name: "ext_workspace_group_handle_v1",
    version: 1,
    method_count: 2,
    methods: addr ext_workspace_group_handle_v1_requests[0],
    event_count: 6,
    events: addr ext_workspace_group_handle_v1_events[0],
  )

  ext_workspace_handle_v1_requests {.exportc.} = [
    Message(name: "destroy", signature: "", types: addr ext_workspace_v1_types[0]),
    Message(name: "activate", signature: "", types: addr ext_workspace_v1_types[0]),
    Message(name: "deactivate", signature: "", types: addr ext_workspace_v1_types[0]),
    Message(name: "assign", signature: "o", types: addr ext_workspace_v1_types[7]),
    Message(name: "remove", signature: "", types: addr ext_workspace_v1_types[0]),
  ]

  ext_workspace_handle_v1_events {.exportc.} = [
    Message(name: "id", signature: "s", types: addr ext_workspace_v1_types[0]),
    Message(name: "name", signature: "s", types: addr ext_workspace_v1_types[0]),
    Message(name: "coordinates", signature: "a", types: addr ext_workspace_v1_types[0]),
    Message(name: "state", signature: "u", types: addr ext_workspace_v1_types[0]),
    Message(name: "capabilities", signature: "u", types: addr ext_workspace_v1_types[0]),
    Message(name: "removed", signature: "", types: addr ext_workspace_v1_types[0]),
  ]

  ext_workspace_handle_v1_interface* {.exportc.} = Interface(
    name: "ext_workspace_handle_v1",
    version: 1,
    method_count: 5,
    methods: addr ext_workspace_handle_v1_requests[0],
    event_count: 6,
    events: addr ext_workspace_handle_v1_events[0],
  )


type ExtWorkspaceGroupHandleV1GroupCapabilities* {.size: sizeof(uint32).} = enum
  group_capabilities_create_workspace = 1
func since*(e: ExtWorkspaceGroupHandleV1GroupCapabilities): int =
  case e
  of group_capabilities_create_workspace: 1
proc isValid*(e: ExtWorkspaceGroupHandleV1GroupCapabilities; version: int): bool =
  version >= e.since

type ExtWorkspaceHandleV1State* {.size: sizeof(uint32).} = enum
  state_active = 1
  state_urgent = 2
  state_hidden = 4
func since*(e: ExtWorkspaceHandleV1State): int =
  case e
  of state_active: 1
  of state_urgent: 1
  of state_hidden: 1
proc isValid*(e: ExtWorkspaceHandleV1State; version: int): bool =
  version >= e.since

type ExtWorkspaceHandleV1WorkspaceCapabilities* {.size: sizeof(uint32).} = enum
  workspace_capabilities_activate = 1
  workspace_capabilities_deactivate = 2
  workspace_capabilities_remove = 4
  workspace_capabilities_assign = 8
func since*(e: ExtWorkspaceHandleV1WorkspaceCapabilities): int =
  case e
  of workspace_capabilities_activate: 1
  of workspace_capabilities_deactivate: 1
  of workspace_capabilities_remove: 1
  of workspace_capabilities_assign: 1
proc isValid*(e: ExtWorkspaceHandleV1WorkspaceCapabilities; version: int): bool =
  version >= e.since

type ExtWorkspaceManagerV1Event* {.size: sizeof(uint32).} = enum
  ExtWorkspaceManagerV1Event_workspace_group
  ExtWorkspaceManagerV1Event_workspace
  ExtWorkspaceManagerV1Event_done
  ExtWorkspaceManagerV1Event_finished
proc since*(e: ExtWorkspaceManagerV1Event): int =
  case e
  of ExtWorkspaceManagerV1Event_workspace_group: 1
  of ExtWorkspaceManagerV1Event_workspace: 1
  of ExtWorkspaceManagerV1Event_done: 1
  of ExtWorkspaceManagerV1Event_finished: 1

type ExtWorkspaceManagerV1Request* {.size: sizeof(uint32).} = enum
  ExtWorkspaceManagerV1Request_commit
  ExtWorkspaceManagerV1Request_stop
proc since*(e: ExtWorkspaceManagerV1Request): int =
  case e
  of ExtWorkspaceManagerV1Request_commit: 1
  of ExtWorkspaceManagerV1Request_stop: 1

type ExtWorkspaceGroupHandleV1Event* {.size: sizeof(uint32).} = enum
  ExtWorkspaceGroupHandleV1Event_capabilities
  ExtWorkspaceGroupHandleV1Event_output_enter
  ExtWorkspaceGroupHandleV1Event_output_leave
  ExtWorkspaceGroupHandleV1Event_workspace_enter
  ExtWorkspaceGroupHandleV1Event_workspace_leave
  ExtWorkspaceGroupHandleV1Event_removed
proc since*(e: ExtWorkspaceGroupHandleV1Event): int =
  case e
  of ExtWorkspaceGroupHandleV1Event_capabilities: 1
  of ExtWorkspaceGroupHandleV1Event_output_enter: 1
  of ExtWorkspaceGroupHandleV1Event_output_leave: 1
  of ExtWorkspaceGroupHandleV1Event_workspace_enter: 1
  of ExtWorkspaceGroupHandleV1Event_workspace_leave: 1
  of ExtWorkspaceGroupHandleV1Event_removed: 1

type ExtWorkspaceGroupHandleV1Request* {.size: sizeof(uint32).} = enum
  ExtWorkspaceGroupHandleV1Request_create_workspace
  ExtWorkspaceGroupHandleV1Request_destroy
proc since*(e: ExtWorkspaceGroupHandleV1Request): int =
  case e
  of ExtWorkspaceGroupHandleV1Request_create_workspace: 1
  of ExtWorkspaceGroupHandleV1Request_destroy: 1

type ExtWorkspaceHandleV1Event* {.size: sizeof(uint32).} = enum
  ExtWorkspaceHandleV1Event_id
  ExtWorkspaceHandleV1Event_name
  ExtWorkspaceHandleV1Event_coordinates
  ExtWorkspaceHandleV1Event_state
  ExtWorkspaceHandleV1Event_capabilities
  ExtWorkspaceHandleV1Event_removed
proc since*(e: ExtWorkspaceHandleV1Event): int =
  case e
  of ExtWorkspaceHandleV1Event_id: 1
  of ExtWorkspaceHandleV1Event_name: 1
  of ExtWorkspaceHandleV1Event_coordinates: 1
  of ExtWorkspaceHandleV1Event_state: 1
  of ExtWorkspaceHandleV1Event_capabilities: 1
  of ExtWorkspaceHandleV1Event_removed: 1

type ExtWorkspaceHandleV1Request* {.size: sizeof(uint32).} = enum
  ExtWorkspaceHandleV1Request_destroy
  ExtWorkspaceHandleV1Request_activate
  ExtWorkspaceHandleV1Request_deactivate
  ExtWorkspaceHandleV1Request_assign
  ExtWorkspaceHandleV1Request_remove
proc since*(e: ExtWorkspaceHandleV1Request): int =
  case e
  of ExtWorkspaceHandleV1Request_destroy: 1
  of ExtWorkspaceHandleV1Request_activate: 1
  of ExtWorkspaceHandleV1Request_deactivate: 1
  of ExtWorkspaceHandleV1Request_assign: 1
  of ExtWorkspaceHandleV1Request_remove: 1

extWorkspaceV1_types = [
  nil,
  addr ext_workspace_group_handle_v1_interface,
  addr ext_workspace_handle_v1_interface,
  addr wl_output_interface,
  addr wl_output_interface,
  addr ext_workspace_handle_v1_interface,
  addr ext_workspace_handle_v1_interface,
  addr ext_workspace_group_handle_v1_interface,
]


