# Generated by wayland-nim-scanner 1.23.1
{.warning[UnusedImport]:off.}
import wayland/native/common
import wayland/protocols/wayland/code as wayland_code

var singlePixelBufferV1_types: array[5, ptr Interface]
type WpSinglePixelBufferManagerV1* = object

let
  wp_single_pixel_buffer_manager_v1_requests {.exportc.} = [
    Message(name: "destroy", signature: "", types: addr single_pixel_buffer_v1_types[0]),
    Message(name: "create_u32_rgba_buffer", signature: "nuuuu", types: addr single_pixel_buffer_v1_types[0]),
  ]

  wp_single_pixel_buffer_manager_v1_interface* {.exportc.} = Interface(
    name: "wp_single_pixel_buffer_manager_v1",
    version: 1,
    method_count: 2,
    methods: addr wp_single_pixel_buffer_manager_v1_requests[0],
  )


type WpSinglePixelBufferManagerV1Request* {.size: sizeof(uint32).} = enum
  WpSinglePixelBufferManagerV1Request_destroy
  WpSinglePixelBufferManagerV1Request_create_u32_rgba_buffer
proc since*(e: WpSinglePixelBufferManagerV1Request): int =
  case e
  of WpSinglePixelBufferManagerV1Request_destroy: 1
  of WpSinglePixelBufferManagerV1Request_create_u32_rgba_buffer: 1

singlePixelBufferV1_types = [
  addr wl_buffer_interface,
  nil,
  nil,
  nil,
  nil,
]


