# Generated by wayland-nim-scanner 1.23.1
{.warning[UnusedImport]:off.}
import wayland/native/common
import wayland/protocols/wayland/code as wayland_code

var colorManagementV1_types: array[25, ptr Interface]
type WpColorManagementOutputV1* = object
type WpColorManagementSurfaceFeedbackV1* = object
type WpColorManagementSurfaceV1* = object
type WpColorManagerV1* = object
type WpImageDescriptionCreatorIccV1* = object
type WpImageDescriptionCreatorParamsV1* = object
type WpImageDescriptionInfoV1* = object
type WpImageDescriptionV1* = object

let
  wp_color_manager_v1_requests {.exportc.} = [
    Message(name: "destroy", signature: "", types: addr color_management_v1_types[0]),
    Message(name: "get_output", signature: "no", types: addr color_management_v1_types[8]),
    Message(name: "get_surface", signature: "no", types: addr color_management_v1_types[10]),
    Message(name: "get_surface_feedback", signature: "no", types: addr color_management_v1_types[12]),
    Message(name: "create_icc_creator", signature: "n", types: addr color_management_v1_types[14]),
    Message(name: "create_parametric_creator", signature: "n", types: addr color_management_v1_types[15]),
    Message(name: "create_windows_scrgb", signature: "n", types: addr color_management_v1_types[16]),
  ]

  wp_color_manager_v1_events {.exportc.} = [
    Message(name: "supported_intent", signature: "u", types: addr color_management_v1_types[0]),
    Message(name: "supported_feature", signature: "u", types: addr color_management_v1_types[0]),
    Message(name: "supported_tf_named", signature: "u", types: addr color_management_v1_types[0]),
    Message(name: "supported_primaries_named", signature: "u", types: addr color_management_v1_types[0]),
    Message(name: "done", signature: "", types: addr color_management_v1_types[0]),
  ]

  wp_color_manager_v1_interface* {.exportc.} = Interface(
    name: "wp_color_manager_v1",
    version: 1,
    method_count: 7,
    methods: addr wp_color_manager_v1_requests[0],
    event_count: 5,
    events: addr wp_color_manager_v1_events[0],
  )

  wp_color_management_output_v1_requests {.exportc.} = [
    Message(name: "destroy", signature: "", types: addr color_management_v1_types[0]),
    Message(name: "get_image_description", signature: "n", types: addr color_management_v1_types[17]),
  ]

  wp_color_management_output_v1_events {.exportc.} = [
    Message(name: "image_description_changed", signature: "", types: addr color_management_v1_types[0]),
  ]

  wp_color_management_output_v1_interface* {.exportc.} = Interface(
    name: "wp_color_management_output_v1",
    version: 1,
    method_count: 2,
    methods: addr wp_color_management_output_v1_requests[0],
    event_count: 1,
    events: addr wp_color_management_output_v1_events[0],
  )

  wp_color_management_surface_v1_requests {.exportc.} = [
    Message(name: "destroy", signature: "", types: addr color_management_v1_types[0]),
    Message(name: "set_image_description", signature: "ou", types: addr color_management_v1_types[18]),
    Message(name: "unset_image_description", signature: "", types: addr color_management_v1_types[0]),
  ]

  wp_color_management_surface_v1_interface* {.exportc.} = Interface(
    name: "wp_color_management_surface_v1",
    version: 1,
    method_count: 3,
    methods: addr wp_color_management_surface_v1_requests[0],
  )

  wp_color_management_surface_feedback_v1_requests {.exportc.} = [
    Message(name: "destroy", signature: "", types: addr color_management_v1_types[0]),
    Message(name: "get_preferred", signature: "n", types: addr color_management_v1_types[20]),
    Message(name: "get_preferred_parametric", signature: "n", types: addr color_management_v1_types[21]),
  ]

  wp_color_management_surface_feedback_v1_events {.exportc.} = [
    Message(name: "preferred_changed", signature: "u", types: addr color_management_v1_types[0]),
  ]

  wp_color_management_surface_feedback_v1_interface* {.exportc.} = Interface(
    name: "wp_color_management_surface_feedback_v1",
    version: 1,
    method_count: 3,
    methods: addr wp_color_management_surface_feedback_v1_requests[0],
    event_count: 1,
    events: addr wp_color_management_surface_feedback_v1_events[0],
  )

  wp_image_description_creator_icc_v1_requests {.exportc.} = [
    Message(name: "create", signature: "n", types: addr color_management_v1_types[22]),
    Message(name: "set_icc_file", signature: "huu", types: addr color_management_v1_types[0]),
  ]

  wp_image_description_creator_icc_v1_interface* {.exportc.} = Interface(
    name: "wp_image_description_creator_icc_v1",
    version: 1,
    method_count: 2,
    methods: addr wp_image_description_creator_icc_v1_requests[0],
  )

  wp_image_description_creator_params_v1_requests {.exportc.} = [
    Message(name: "create", signature: "n", types: addr color_management_v1_types[23]),
    Message(name: "set_tf_named", signature: "u", types: addr color_management_v1_types[0]),
    Message(name: "set_tf_power", signature: "u", types: addr color_management_v1_types[0]),
    Message(name: "set_primaries_named", signature: "u", types: addr color_management_v1_types[0]),
    Message(name: "set_primaries", signature: "iiiiiiii", types: addr color_management_v1_types[0]),
    Message(name: "set_luminances", signature: "uuu", types: addr color_management_v1_types[0]),
    Message(name: "set_mastering_display_primaries", signature: "iiiiiiii", types: addr color_management_v1_types[0]),
    Message(name: "set_mastering_luminance", signature: "uu", types: addr color_management_v1_types[0]),
    Message(name: "set_max_cll", signature: "u", types: addr color_management_v1_types[0]),
    Message(name: "set_max_fall", signature: "u", types: addr color_management_v1_types[0]),
  ]

  wp_image_description_creator_params_v1_interface* {.exportc.} = Interface(
    name: "wp_image_description_creator_params_v1",
    version: 1,
    method_count: 10,
    methods: addr wp_image_description_creator_params_v1_requests[0],
  )

  wp_image_description_v1_requests {.exportc.} = [
    Message(name: "destroy", signature: "", types: addr color_management_v1_types[0]),
    Message(name: "get_information", signature: "n", types: addr color_management_v1_types[24]),
  ]

  wp_image_description_v1_events {.exportc.} = [
    Message(name: "failed", signature: "us", types: addr color_management_v1_types[0]),
    Message(name: "ready", signature: "u", types: addr color_management_v1_types[0]),
  ]

  wp_image_description_v1_interface* {.exportc.} = Interface(
    name: "wp_image_description_v1",
    version: 1,
    method_count: 2,
    methods: addr wp_image_description_v1_requests[0],
    event_count: 2,
    events: addr wp_image_description_v1_events[0],
  )

  wp_image_description_info_v1_events {.exportc.} = [
    Message(name: "done", signature: "", types: addr color_management_v1_types[0]),
    Message(name: "icc_file", signature: "hu", types: addr color_management_v1_types[0]),
    Message(name: "primaries", signature: "iiiiiiii", types: addr color_management_v1_types[0]),
    Message(name: "primaries_named", signature: "u", types: addr color_management_v1_types[0]),
    Message(name: "tf_power", signature: "u", types: addr color_management_v1_types[0]),
    Message(name: "tf_named", signature: "u", types: addr color_management_v1_types[0]),
    Message(name: "luminances", signature: "uuu", types: addr color_management_v1_types[0]),
    Message(name: "target_primaries", signature: "iiiiiiii", types: addr color_management_v1_types[0]),
    Message(name: "target_luminance", signature: "uu", types: addr color_management_v1_types[0]),
    Message(name: "target_max_cll", signature: "u", types: addr color_management_v1_types[0]),
    Message(name: "target_max_fall", signature: "u", types: addr color_management_v1_types[0]),
  ]

  wp_image_description_info_v1_interface* {.exportc.} = Interface(
    name: "wp_image_description_info_v1",
    version: 1,
    event_count: 11,
    events: addr wp_image_description_info_v1_events[0],
  )


type WpColorManagerV1Error* {.size: sizeof(uint32).} = enum
  error_unsupported_feature = 0
  error_surface_exists = 1
func since*(e: WpColorManagerV1Error): int =
  case e
  of error_unsupported_feature: 1
  of error_surface_exists: 1
proc isValid*(e: WpColorManagerV1Error; version: int): bool =
  version >= e.since

type WpColorManagerV1RenderIntent* {.size: sizeof(uint32).} = enum
  render_intent_perceptual = 0
  render_intent_relative = 1
  render_intent_saturation = 2
  render_intent_absolute = 3
  render_intent_relative_bpc = 4
func since*(e: WpColorManagerV1RenderIntent): int =
  case e
  of render_intent_perceptual: 1
  of render_intent_relative: 1
  of render_intent_saturation: 1
  of render_intent_absolute: 1
  of render_intent_relative_bpc: 1
proc isValid*(e: WpColorManagerV1RenderIntent; version: int): bool =
  version >= e.since

type WpColorManagerV1Feature* {.size: sizeof(uint32).} = enum
  feature_icc_v2_v4 = 0
  feature_parametric = 1
  feature_set_primaries = 2
  feature_set_tf_power = 3
  feature_set_luminances = 4
  feature_set_mastering_display_primaries = 5
  feature_extended_target_volume = 6
  feature_windows_scrgb = 7
func since*(e: WpColorManagerV1Feature): int =
  case e
  of feature_icc_v2_v4: 1
  of feature_parametric: 1
  of feature_set_primaries: 1
  of feature_set_tf_power: 1
  of feature_set_luminances: 1
  of feature_set_mastering_display_primaries: 1
  of feature_extended_target_volume: 1
  of feature_windows_scrgb: 1
proc isValid*(e: WpColorManagerV1Feature; version: int): bool =
  version >= e.since

type WpColorManagerV1Primaries* {.size: sizeof(uint32).} = enum
  primaries_srgb = 1
  primaries_pal_m = 2
  primaries_pal = 3
  primaries_ntsc = 4
  primaries_generic_film = 5
  primaries_bt2020 = 6
  primaries_cie1931_xyz = 7
  primaries_dci_p3 = 8
  primaries_display_p3 = 9
  primaries_adobe_rgb = 10
func since*(e: WpColorManagerV1Primaries): int =
  case e
  of primaries_srgb: 1
  of primaries_pal_m: 1
  of primaries_pal: 1
  of primaries_ntsc: 1
  of primaries_generic_film: 1
  of primaries_bt2020: 1
  of primaries_cie1931_xyz: 1
  of primaries_dci_p3: 1
  of primaries_display_p3: 1
  of primaries_adobe_rgb: 1
proc isValid*(e: WpColorManagerV1Primaries; version: int): bool =
  version >= e.since

type WpColorManagerV1TransferFunction* {.size: sizeof(uint32).} = enum
  transfer_function_bt1886 = 1
  transfer_function_gamma22 = 2
  transfer_function_gamma28 = 3
  transfer_function_st240 = 4
  transfer_function_ext_linear = 5
  transfer_function_log_100 = 6
  transfer_function_log_316 = 7
  transfer_function_xvycc = 8
  transfer_function_srgb = 9
  transfer_function_ext_srgb = 10
  transfer_function_st2084_pq = 11
  transfer_function_st428 = 12
  transfer_function_hlg = 13
func since*(e: WpColorManagerV1TransferFunction): int =
  case e
  of transfer_function_bt1886: 1
  of transfer_function_gamma22: 1
  of transfer_function_gamma28: 1
  of transfer_function_st240: 1
  of transfer_function_ext_linear: 1
  of transfer_function_log_100: 1
  of transfer_function_log_316: 1
  of transfer_function_xvycc: 1
  of transfer_function_srgb: 1
  of transfer_function_ext_srgb: 1
  of transfer_function_st2084_pq: 1
  of transfer_function_st428: 1
  of transfer_function_hlg: 1
proc isValid*(e: WpColorManagerV1TransferFunction; version: int): bool =
  version >= e.since

type WpColorManagementSurfaceV1Error* {.size: sizeof(uint32).} = enum
  error_render_intent = 0
  error_image_description = 1
  error_inert = 2
func since*(e: WpColorManagementSurfaceV1Error): int =
  case e
  of error_render_intent: 1
  of error_image_description: 1
  of error_inert: 1
proc isValid*(e: WpColorManagementSurfaceV1Error; version: int): bool =
  version >= e.since

type WpColorManagementSurfaceFeedbackV1Error* {.size: sizeof(uint32).} = enum
  error_inert = 0
  error_unsupported_feature = 1
func since*(e: WpColorManagementSurfaceFeedbackV1Error): int =
  case e
  of error_inert: 1
  of error_unsupported_feature: 1
proc isValid*(e: WpColorManagementSurfaceFeedbackV1Error; version: int): bool =
  version >= e.since

type WpImageDescriptionCreatorIccV1Error* {.size: sizeof(uint32).} = enum
  error_incomplete_set = 0
  error_already_set = 1
  error_bad_fd = 2
  error_bad_size = 3
  error_out_of_file = 4
func since*(e: WpImageDescriptionCreatorIccV1Error): int =
  case e
  of error_incomplete_set: 1
  of error_already_set: 1
  of error_bad_fd: 1
  of error_bad_size: 1
  of error_out_of_file: 1
proc isValid*(e: WpImageDescriptionCreatorIccV1Error; version: int): bool =
  version >= e.since

type WpImageDescriptionCreatorParamsV1Error* {.size: sizeof(uint32).} = enum
  error_incomplete_set = 0
  error_already_set = 1
  error_unsupported_feature = 2
  error_invalid_tf = 3
  error_invalid_primaries_named = 4
  error_invalid_luminance = 5
func since*(e: WpImageDescriptionCreatorParamsV1Error): int =
  case e
  of error_incomplete_set: 1
  of error_already_set: 1
  of error_unsupported_feature: 1
  of error_invalid_tf: 1
  of error_invalid_primaries_named: 1
  of error_invalid_luminance: 1
proc isValid*(e: WpImageDescriptionCreatorParamsV1Error; version: int): bool =
  version >= e.since

type WpImageDescriptionV1Error* {.size: sizeof(uint32).} = enum
  error_not_ready = 0
  error_no_information = 1
func since*(e: WpImageDescriptionV1Error): int =
  case e
  of error_not_ready: 1
  of error_no_information: 1
proc isValid*(e: WpImageDescriptionV1Error; version: int): bool =
  version >= e.since

type WpImageDescriptionV1Cause* {.size: sizeof(uint32).} = enum
  cause_low_version = 0
  cause_unsupported = 1
  cause_operating_system = 2
  cause_no_output = 3
func since*(e: WpImageDescriptionV1Cause): int =
  case e
  of cause_low_version: 1
  of cause_unsupported: 1
  of cause_operating_system: 1
  of cause_no_output: 1
proc isValid*(e: WpImageDescriptionV1Cause; version: int): bool =
  version >= e.since

type WpColorManagerV1Event* {.size: sizeof(uint32).} = enum
  WpColorManagerV1Event_supported_intent
  WpColorManagerV1Event_supported_feature
  WpColorManagerV1Event_supported_tf_named
  WpColorManagerV1Event_supported_primaries_named
  WpColorManagerV1Event_done
proc since*(e: WpColorManagerV1Event): int =
  case e
  of WpColorManagerV1Event_supported_intent: 1
  of WpColorManagerV1Event_supported_feature: 1
  of WpColorManagerV1Event_supported_tf_named: 1
  of WpColorManagerV1Event_supported_primaries_named: 1
  of WpColorManagerV1Event_done: 1

type WpColorManagerV1Request* {.size: sizeof(uint32).} = enum
  WpColorManagerV1Request_destroy
  WpColorManagerV1Request_get_output
  WpColorManagerV1Request_get_surface
  WpColorManagerV1Request_get_surface_feedback
  WpColorManagerV1Request_create_icc_creator
  WpColorManagerV1Request_create_parametric_creator
  WpColorManagerV1Request_create_windows_scrgb
proc since*(e: WpColorManagerV1Request): int =
  case e
  of WpColorManagerV1Request_destroy: 1
  of WpColorManagerV1Request_get_output: 1
  of WpColorManagerV1Request_get_surface: 1
  of WpColorManagerV1Request_get_surface_feedback: 1
  of WpColorManagerV1Request_create_icc_creator: 1
  of WpColorManagerV1Request_create_parametric_creator: 1
  of WpColorManagerV1Request_create_windows_scrgb: 1

type WpColorManagementOutputV1Event* {.size: sizeof(uint32).} = enum
  WpColorManagementOutputV1Event_image_description_changed
proc since*(e: WpColorManagementOutputV1Event): int =
  case e
  of WpColorManagementOutputV1Event_image_description_changed: 1

type WpColorManagementOutputV1Request* {.size: sizeof(uint32).} = enum
  WpColorManagementOutputV1Request_destroy
  WpColorManagementOutputV1Request_get_image_description
proc since*(e: WpColorManagementOutputV1Request): int =
  case e
  of WpColorManagementOutputV1Request_destroy: 1
  of WpColorManagementOutputV1Request_get_image_description: 1

type WpColorManagementSurfaceV1Request* {.size: sizeof(uint32).} = enum
  WpColorManagementSurfaceV1Request_destroy
  WpColorManagementSurfaceV1Request_set_image_description
  WpColorManagementSurfaceV1Request_unset_image_description
proc since*(e: WpColorManagementSurfaceV1Request): int =
  case e
  of WpColorManagementSurfaceV1Request_destroy: 1
  of WpColorManagementSurfaceV1Request_set_image_description: 1
  of WpColorManagementSurfaceV1Request_unset_image_description: 1

type WpColorManagementSurfaceFeedbackV1Event* {.size: sizeof(uint32).} = enum
  WpColorManagementSurfaceFeedbackV1Event_preferred_changed
proc since*(e: WpColorManagementSurfaceFeedbackV1Event): int =
  case e
  of WpColorManagementSurfaceFeedbackV1Event_preferred_changed: 1

type WpColorManagementSurfaceFeedbackV1Request* {.size: sizeof(uint32).} = enum
  WpColorManagementSurfaceFeedbackV1Request_destroy
  WpColorManagementSurfaceFeedbackV1Request_get_preferred
  WpColorManagementSurfaceFeedbackV1Request_get_preferred_parametric
proc since*(e: WpColorManagementSurfaceFeedbackV1Request): int =
  case e
  of WpColorManagementSurfaceFeedbackV1Request_destroy: 1
  of WpColorManagementSurfaceFeedbackV1Request_get_preferred: 1
  of WpColorManagementSurfaceFeedbackV1Request_get_preferred_parametric: 1

type WpImageDescriptionCreatorIccV1Request* {.size: sizeof(uint32).} = enum
  WpImageDescriptionCreatorIccV1Request_create
  WpImageDescriptionCreatorIccV1Request_set_icc_file
proc since*(e: WpImageDescriptionCreatorIccV1Request): int =
  case e
  of WpImageDescriptionCreatorIccV1Request_create: 1
  of WpImageDescriptionCreatorIccV1Request_set_icc_file: 1

type WpImageDescriptionCreatorParamsV1Request* {.size: sizeof(uint32).} = enum
  WpImageDescriptionCreatorParamsV1Request_create
  WpImageDescriptionCreatorParamsV1Request_set_tf_named
  WpImageDescriptionCreatorParamsV1Request_set_tf_power
  WpImageDescriptionCreatorParamsV1Request_set_primaries_named
  WpImageDescriptionCreatorParamsV1Request_set_primaries
  WpImageDescriptionCreatorParamsV1Request_set_luminances
  WpImageDescriptionCreatorParamsV1Request_set_mastering_display_primaries
  WpImageDescriptionCreatorParamsV1Request_set_mastering_luminance
  WpImageDescriptionCreatorParamsV1Request_set_max_cll
  WpImageDescriptionCreatorParamsV1Request_set_max_fall
proc since*(e: WpImageDescriptionCreatorParamsV1Request): int =
  case e
  of WpImageDescriptionCreatorParamsV1Request_create: 1
  of WpImageDescriptionCreatorParamsV1Request_set_tf_named: 1
  of WpImageDescriptionCreatorParamsV1Request_set_tf_power: 1
  of WpImageDescriptionCreatorParamsV1Request_set_primaries_named: 1
  of WpImageDescriptionCreatorParamsV1Request_set_primaries: 1
  of WpImageDescriptionCreatorParamsV1Request_set_luminances: 1
  of WpImageDescriptionCreatorParamsV1Request_set_mastering_display_primaries: 1
  of WpImageDescriptionCreatorParamsV1Request_set_mastering_luminance: 1
  of WpImageDescriptionCreatorParamsV1Request_set_max_cll: 1
  of WpImageDescriptionCreatorParamsV1Request_set_max_fall: 1

type WpImageDescriptionV1Event* {.size: sizeof(uint32).} = enum
  WpImageDescriptionV1Event_failed
  WpImageDescriptionV1Event_ready
proc since*(e: WpImageDescriptionV1Event): int =
  case e
  of WpImageDescriptionV1Event_failed: 1
  of WpImageDescriptionV1Event_ready: 1

type WpImageDescriptionV1Request* {.size: sizeof(uint32).} = enum
  WpImageDescriptionV1Request_destroy
  WpImageDescriptionV1Request_get_information
proc since*(e: WpImageDescriptionV1Request): int =
  case e
  of WpImageDescriptionV1Request_destroy: 1
  of WpImageDescriptionV1Request_get_information: 1

type WpImageDescriptionInfoV1Event* {.size: sizeof(uint32).} = enum
  WpImageDescriptionInfoV1Event_done
  WpImageDescriptionInfoV1Event_icc_file
  WpImageDescriptionInfoV1Event_primaries
  WpImageDescriptionInfoV1Event_primaries_named
  WpImageDescriptionInfoV1Event_tf_power
  WpImageDescriptionInfoV1Event_tf_named
  WpImageDescriptionInfoV1Event_luminances
  WpImageDescriptionInfoV1Event_target_primaries
  WpImageDescriptionInfoV1Event_target_luminance
  WpImageDescriptionInfoV1Event_target_max_cll
  WpImageDescriptionInfoV1Event_target_max_fall
proc since*(e: WpImageDescriptionInfoV1Event): int =
  case e
  of WpImageDescriptionInfoV1Event_done: 1
  of WpImageDescriptionInfoV1Event_icc_file: 1
  of WpImageDescriptionInfoV1Event_primaries: 1
  of WpImageDescriptionInfoV1Event_primaries_named: 1
  of WpImageDescriptionInfoV1Event_tf_power: 1
  of WpImageDescriptionInfoV1Event_tf_named: 1
  of WpImageDescriptionInfoV1Event_luminances: 1
  of WpImageDescriptionInfoV1Event_target_primaries: 1
  of WpImageDescriptionInfoV1Event_target_luminance: 1
  of WpImageDescriptionInfoV1Event_target_max_cll: 1
  of WpImageDescriptionInfoV1Event_target_max_fall: 1

colorManagementV1_types = [
  nil,
  nil,
  nil,
  nil,
  nil,
  nil,
  nil,
  nil,
  addr wp_color_management_output_v1_interface,
  addr wl_output_interface,
  addr wp_color_management_surface_v1_interface,
  addr wl_surface_interface,
  addr wp_color_management_surface_feedback_v1_interface,
  addr wl_surface_interface,
  addr wp_image_description_creator_icc_v1_interface,
  addr wp_image_description_creator_params_v1_interface,
  addr wp_image_description_v1_interface,
  addr wp_image_description_v1_interface,
  addr wp_image_description_v1_interface,
  nil,
  addr wp_image_description_v1_interface,
  addr wp_image_description_v1_interface,
  addr wp_image_description_v1_interface,
  addr wp_image_description_v1_interface,
  addr wp_image_description_info_v1_interface,
]


