# Generated by wayland-nim-scanner 1.23.1
{.warning[UnusedImport]:off.}
import wayland/native/common
import wayland/protocols/wayland/code as wayland_code

var linuxDmabufUnstableV1_types: array[16, ptr Interface]
type ZwpLinuxBufferParamsV1* = object
type ZwpLinuxDmabufFeedbackV1* = object
type ZwpLinuxDmabufV1* = object

let
  zwp_linux_dmabuf_v1_requests {.exportc.} = [
    Message(name: "destroy", signature: "", types: addr linux_dmabuf_unstable_v1_types[0]),
    Message(name: "create_params", signature: "n", types: addr linux_dmabuf_unstable_v1_types[6]),
    Message(name: "get_default_feedback", signature: "4n", types: addr linux_dmabuf_unstable_v1_types[7]),
    Message(name: "get_surface_feedback", signature: "4no", types: addr linux_dmabuf_unstable_v1_types[8]),
  ]

  zwp_linux_dmabuf_v1_events {.exportc.} = [
    Message(name: "format", signature: "u", types: addr linux_dmabuf_unstable_v1_types[0]),
    Message(name: "modifier", signature: "3uuu", types: addr linux_dmabuf_unstable_v1_types[0]),
  ]

  zwp_linux_dmabuf_v1_interface* {.exportc.} = Interface(
    name: "zwp_linux_dmabuf_v1",
    version: 5,
    method_count: 4,
    methods: addr zwp_linux_dmabuf_v1_requests[0],
    event_count: 2,
    events: addr zwp_linux_dmabuf_v1_events[0],
  )

  zwp_linux_buffer_params_v1_requests {.exportc.} = [
    Message(name: "destroy", signature: "", types: addr linux_dmabuf_unstable_v1_types[0]),
    Message(name: "add", signature: "huuuuu", types: addr linux_dmabuf_unstable_v1_types[0]),
    Message(name: "create", signature: "iiuu", types: addr linux_dmabuf_unstable_v1_types[0]),
    Message(name: "create_immed", signature: "2niiuu", types: addr linux_dmabuf_unstable_v1_types[10]),
  ]

  zwp_linux_buffer_params_v1_events {.exportc.} = [
    Message(name: "created", signature: "n", types: addr linux_dmabuf_unstable_v1_types[15]),
    Message(name: "failed", signature: "", types: addr linux_dmabuf_unstable_v1_types[0]),
  ]

  zwp_linux_buffer_params_v1_interface* {.exportc.} = Interface(
    name: "zwp_linux_buffer_params_v1",
    version: 5,
    method_count: 4,
    methods: addr zwp_linux_buffer_params_v1_requests[0],
    event_count: 2,
    events: addr zwp_linux_buffer_params_v1_events[0],
  )

  zwp_linux_dmabuf_feedback_v1_requests {.exportc.} = [
    Message(name: "destroy", signature: "", types: addr linux_dmabuf_unstable_v1_types[0]),
  ]

  zwp_linux_dmabuf_feedback_v1_events {.exportc.} = [
    Message(name: "done", signature: "", types: addr linux_dmabuf_unstable_v1_types[0]),
    Message(name: "format_table", signature: "hu", types: addr linux_dmabuf_unstable_v1_types[0]),
    Message(name: "main_device", signature: "a", types: addr linux_dmabuf_unstable_v1_types[0]),
    Message(name: "tranche_done", signature: "", types: addr linux_dmabuf_unstable_v1_types[0]),
    Message(name: "tranche_target_device", signature: "a", types: addr linux_dmabuf_unstable_v1_types[0]),
    Message(name: "tranche_formats", signature: "a", types: addr linux_dmabuf_unstable_v1_types[0]),
    Message(name: "tranche_flags", signature: "u", types: addr linux_dmabuf_unstable_v1_types[0]),
  ]

  zwp_linux_dmabuf_feedback_v1_interface* {.exportc.} = Interface(
    name: "zwp_linux_dmabuf_feedback_v1",
    version: 5,
    method_count: 1,
    methods: addr zwp_linux_dmabuf_feedback_v1_requests[0],
    event_count: 7,
    events: addr zwp_linux_dmabuf_feedback_v1_events[0],
  )


type ZwpLinuxBufferParamsV1Error* {.size: sizeof(uint32).} = enum
  error_already_used = 0
  error_plane_idx = 1
  error_plane_set = 2
  error_incomplete = 3
  error_invalid_format = 4
  error_invalid_dimensions = 5
  error_out_of_bounds = 6
  error_invalid_wl_buffer = 7
func since*(e: ZwpLinuxBufferParamsV1Error): int =
  case e
  of error_already_used: 1
  of error_plane_idx: 1
  of error_plane_set: 1
  of error_incomplete: 1
  of error_invalid_format: 1
  of error_invalid_dimensions: 1
  of error_out_of_bounds: 1
  of error_invalid_wl_buffer: 1
proc isValid*(e: ZwpLinuxBufferParamsV1Error; version: int): bool =
  version >= e.since

type ZwpLinuxBufferParamsV1Flags* {.size: sizeof(uint32).} = enum
  flags_y_invert = 1
  flags_interlaced = 2
  flags_bottom_first = 4
func since*(e: ZwpLinuxBufferParamsV1Flags): int =
  case e
  of flags_y_invert: 1
  of flags_interlaced: 1
  of flags_bottom_first: 1
proc isValid*(e: ZwpLinuxBufferParamsV1Flags; version: int): bool =
  version >= e.since

type ZwpLinuxDmabufFeedbackV1TrancheFlags* {.size: sizeof(uint32).} = enum
  tranche_flags_scanout = 1
func since*(e: ZwpLinuxDmabufFeedbackV1TrancheFlags): int =
  case e
  of tranche_flags_scanout: 1
proc isValid*(e: ZwpLinuxDmabufFeedbackV1TrancheFlags; version: int): bool =
  version >= e.since

type ZwpLinuxDmabufV1Event* {.size: sizeof(uint32).} = enum
  ZwpLinuxDmabufV1Event_format
  ZwpLinuxDmabufV1Event_modifier
proc since*(e: ZwpLinuxDmabufV1Event): int =
  case e
  of ZwpLinuxDmabufV1Event_format: 1
  of ZwpLinuxDmabufV1Event_modifier: 3

type ZwpLinuxDmabufV1Request* {.size: sizeof(uint32).} = enum
  ZwpLinuxDmabufV1Request_destroy
  ZwpLinuxDmabufV1Request_create_params
  ZwpLinuxDmabufV1Request_get_default_feedback
  ZwpLinuxDmabufV1Request_get_surface_feedback
proc since*(e: ZwpLinuxDmabufV1Request): int =
  case e
  of ZwpLinuxDmabufV1Request_destroy: 1
  of ZwpLinuxDmabufV1Request_create_params: 1
  of ZwpLinuxDmabufV1Request_get_default_feedback: 4
  of ZwpLinuxDmabufV1Request_get_surface_feedback: 4

type ZwpLinuxBufferParamsV1Event* {.size: sizeof(uint32).} = enum
  ZwpLinuxBufferParamsV1Event_created
  ZwpLinuxBufferParamsV1Event_failed
proc since*(e: ZwpLinuxBufferParamsV1Event): int =
  case e
  of ZwpLinuxBufferParamsV1Event_created: 1
  of ZwpLinuxBufferParamsV1Event_failed: 1

type ZwpLinuxBufferParamsV1Request* {.size: sizeof(uint32).} = enum
  ZwpLinuxBufferParamsV1Request_destroy
  ZwpLinuxBufferParamsV1Request_add
  ZwpLinuxBufferParamsV1Request_create
  ZwpLinuxBufferParamsV1Request_create_immed
proc since*(e: ZwpLinuxBufferParamsV1Request): int =
  case e
  of ZwpLinuxBufferParamsV1Request_destroy: 1
  of ZwpLinuxBufferParamsV1Request_add: 1
  of ZwpLinuxBufferParamsV1Request_create: 1
  of ZwpLinuxBufferParamsV1Request_create_immed: 2

type ZwpLinuxDmabufFeedbackV1Event* {.size: sizeof(uint32).} = enum
  ZwpLinuxDmabufFeedbackV1Event_done
  ZwpLinuxDmabufFeedbackV1Event_format_table
  ZwpLinuxDmabufFeedbackV1Event_main_device
  ZwpLinuxDmabufFeedbackV1Event_tranche_done
  ZwpLinuxDmabufFeedbackV1Event_tranche_target_device
  ZwpLinuxDmabufFeedbackV1Event_tranche_formats
  ZwpLinuxDmabufFeedbackV1Event_tranche_flags
proc since*(e: ZwpLinuxDmabufFeedbackV1Event): int =
  case e
  of ZwpLinuxDmabufFeedbackV1Event_done: 1
  of ZwpLinuxDmabufFeedbackV1Event_format_table: 1
  of ZwpLinuxDmabufFeedbackV1Event_main_device: 1
  of ZwpLinuxDmabufFeedbackV1Event_tranche_done: 1
  of ZwpLinuxDmabufFeedbackV1Event_tranche_target_device: 1
  of ZwpLinuxDmabufFeedbackV1Event_tranche_formats: 1
  of ZwpLinuxDmabufFeedbackV1Event_tranche_flags: 1

type ZwpLinuxDmabufFeedbackV1Request* {.size: sizeof(uint32).} = enum
  ZwpLinuxDmabufFeedbackV1Request_destroy
proc since*(e: ZwpLinuxDmabufFeedbackV1Request): int =
  case e
  of ZwpLinuxDmabufFeedbackV1Request_destroy: 1

linuxDmabufUnstableV1_types = [
  nil,
  nil,
  nil,
  nil,
  nil,
  nil,
  addr zwp_linux_buffer_params_v1_interface,
  addr zwp_linux_dmabuf_feedback_v1_interface,
  addr zwp_linux_dmabuf_feedback_v1_interface,
  addr wl_surface_interface,
  addr wl_buffer_interface,
  nil,
  nil,
  nil,
  nil,
  addr wl_buffer_interface,
]


