# Generated by wayland-nim-scanner 1.23.1
{.warning[UnusedImport]:off.}
import wayland/native/common
import wayland/protocols/wayland/code as wayland_code

var contentTypeV1_types: array[3, ptr Interface]
type WpContentTypeManagerV1* = object
type WpContentTypeV1* = object

let
  wp_content_type_manager_v1_requests {.exportc.} = [
    Message(name: "destroy", signature: "", types: addr content_type_v1_types[0]),
    Message(name: "get_surface_content_type", signature: "no", types: addr content_type_v1_types[1]),
  ]

  wp_content_type_manager_v1_interface* {.exportc.} = Interface(
    name: "wp_content_type_manager_v1",
    version: 1,
    method_count: 2,
    methods: addr wp_content_type_manager_v1_requests[0],
  )

  wp_content_type_v1_requests {.exportc.} = [
    Message(name: "destroy", signature: "", types: addr content_type_v1_types[0]),
    Message(name: "set_content_type", signature: "u", types: addr content_type_v1_types[0]),
  ]

  wp_content_type_v1_interface* {.exportc.} = Interface(
    name: "wp_content_type_v1",
    version: 1,
    method_count: 2,
    methods: addr wp_content_type_v1_requests[0],
  )


type WpContentTypeManagerV1Error* {.size: sizeof(uint32).} = enum
  error_already_constructed = 0
func since*(e: WpContentTypeManagerV1Error): int =
  case e
  of error_already_constructed: 1
proc isValid*(e: WpContentTypeManagerV1Error; version: int): bool =
  version >= e.since

type WpContentTypeV1Type* {.size: sizeof(uint32).} = enum
  type_none = 0
  type_photo = 1
  type_video = 2
  type_game = 3
func since*(e: WpContentTypeV1Type): int =
  case e
  of type_none: 1
  of type_photo: 1
  of type_video: 1
  of type_game: 1
proc isValid*(e: WpContentTypeV1Type; version: int): bool =
  version >= e.since

type WpContentTypeManagerV1Request* {.size: sizeof(uint32).} = enum
  WpContentTypeManagerV1Request_destroy
  WpContentTypeManagerV1Request_get_surface_content_type
proc since*(e: WpContentTypeManagerV1Request): int =
  case e
  of WpContentTypeManagerV1Request_destroy: 1
  of WpContentTypeManagerV1Request_get_surface_content_type: 1

type WpContentTypeV1Request* {.size: sizeof(uint32).} = enum
  WpContentTypeV1Request_destroy
  WpContentTypeV1Request_set_content_type
proc since*(e: WpContentTypeV1Request): int =
  case e
  of WpContentTypeV1Request_destroy: 1
  of WpContentTypeV1Request_set_content_type: 1

contentTypeV1_types = [
  nil,
  addr wp_content_type_v1_interface,
  addr wl_surface_interface,
]


