# Generated by wayland-nim-scanner 1.23.1
{.warning[UnusedImport]:off.}
import wayland/native/common
import wayland/protocols/wayland/code as wayland_code

var extForeignToplevelListV1_types: array[2, ptr Interface]
type ExtForeignToplevelHandleV1* = object
type ExtForeignToplevelListV1* = object

let
  ext_foreign_toplevel_list_v1_requests {.exportc.} = [
    Message(name: "stop", signature: "", types: addr ext_foreign_toplevel_list_v1_types[0]),
    Message(name: "destroy", signature: "", types: addr ext_foreign_toplevel_list_v1_types[0]),
  ]

  ext_foreign_toplevel_list_v1_events {.exportc.} = [
    Message(name: "toplevel", signature: "n", types: addr ext_foreign_toplevel_list_v1_types[1]),
    Message(name: "finished", signature: "", types: addr ext_foreign_toplevel_list_v1_types[0]),
  ]

  ext_foreign_toplevel_list_v1_interface* {.exportc.} = Interface(
    name: "ext_foreign_toplevel_list_v1",
    version: 1,
    method_count: 2,
    methods: addr ext_foreign_toplevel_list_v1_requests[0],
    event_count: 2,
    events: addr ext_foreign_toplevel_list_v1_events[0],
  )

  ext_foreign_toplevel_handle_v1_requests {.exportc.} = [
    Message(name: "destroy", signature: "", types: addr ext_foreign_toplevel_list_v1_types[0]),
  ]

  ext_foreign_toplevel_handle_v1_events {.exportc.} = [
    Message(name: "closed", signature: "", types: addr ext_foreign_toplevel_list_v1_types[0]),
    Message(name: "done", signature: "", types: addr ext_foreign_toplevel_list_v1_types[0]),
    Message(name: "title", signature: "s", types: addr ext_foreign_toplevel_list_v1_types[0]),
    Message(name: "app_id", signature: "s", types: addr ext_foreign_toplevel_list_v1_types[0]),
    Message(name: "identifier", signature: "s", types: addr ext_foreign_toplevel_list_v1_types[0]),
  ]

  ext_foreign_toplevel_handle_v1_interface* {.exportc.} = Interface(
    name: "ext_foreign_toplevel_handle_v1",
    version: 1,
    method_count: 1,
    methods: addr ext_foreign_toplevel_handle_v1_requests[0],
    event_count: 5,
    events: addr ext_foreign_toplevel_handle_v1_events[0],
  )


type ExtForeignToplevelListV1Event* {.size: sizeof(uint32).} = enum
  ExtForeignToplevelListV1Event_toplevel
  ExtForeignToplevelListV1Event_finished
proc since*(e: ExtForeignToplevelListV1Event): int =
  case e
  of ExtForeignToplevelListV1Event_toplevel: 1
  of ExtForeignToplevelListV1Event_finished: 1

type ExtForeignToplevelListV1Request* {.size: sizeof(uint32).} = enum
  ExtForeignToplevelListV1Request_stop
  ExtForeignToplevelListV1Request_destroy
proc since*(e: ExtForeignToplevelListV1Request): int =
  case e
  of ExtForeignToplevelListV1Request_stop: 1
  of ExtForeignToplevelListV1Request_destroy: 1

type ExtForeignToplevelHandleV1Event* {.size: sizeof(uint32).} = enum
  ExtForeignToplevelHandleV1Event_closed
  ExtForeignToplevelHandleV1Event_done
  ExtForeignToplevelHandleV1Event_title
  ExtForeignToplevelHandleV1Event_app_id
  ExtForeignToplevelHandleV1Event_identifier
proc since*(e: ExtForeignToplevelHandleV1Event): int =
  case e
  of ExtForeignToplevelHandleV1Event_closed: 1
  of ExtForeignToplevelHandleV1Event_done: 1
  of ExtForeignToplevelHandleV1Event_title: 1
  of ExtForeignToplevelHandleV1Event_app_id: 1
  of ExtForeignToplevelHandleV1Event_identifier: 1

type ExtForeignToplevelHandleV1Request* {.size: sizeof(uint32).} = enum
  ExtForeignToplevelHandleV1Request_destroy
proc since*(e: ExtForeignToplevelHandleV1Request): int =
  case e
  of ExtForeignToplevelHandleV1Request_destroy: 1

extForeignToplevelListV1_types = [
  nil,
  addr ext_foreign_toplevel_handle_v1_interface,
]


