# Generated by wayland-nim-scanner 1.23.1
{.warning[UnusedImport]:off.}
import wayland/native/server
import wayland/native/common
import code
export code

## The ext_idle_notify_v1 SERVER protocol
## ######################################
## 
## Interfaces
## ==========
## 
## * ext_idle_notifier_v1
## * ext_idle_notification_v1
## 
## Copyright
## =========
## 
## Copyright © 2015 Martin Gräßlin
## Copyright © 2022 Simon Ser
## 
## Permission is hereby granted, free of charge, to any person obtaining a
## copy of this software and associated documentation files (the "Software"),
## to deal in the Software without restriction, including without limitation
## the rights to use, copy, modify, merge, publish, distribute, sublicense,
## and/or sell copies of the Software, and to permit persons to whom the
## Software is furnished to do so, subject to the following conditions:
## 
## The above copyright notice and this permission notice (including the next
## paragraph) shall be included in all copies or substantial portions of the
## Software.
## 
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
## IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
## FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
## THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
## LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
## FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
## DEALINGS IN THE SOFTWARE.
## 

type ExtIdleNotifierV1Interface* = object
  destroy*: proc(
    client: ptr Client;
    resource: ptr Resource;
  ) {.nimcall.}
  getIdleNotification*: proc(
    client: ptr Client;
    resource: ptr Resource;
    id: uint32;
    timeout: uint32;
    seat: ptr Resource;
  ) {.nimcall.}
  getInputIdleNotification*: proc(
    client: ptr Client;
    resource: ptr Resource;
    id: uint32;
    timeout: uint32;
    seat: ptr Resource;
  ) {.nimcall.}

type ExtIdleNotificationV1Interface* = object
  destroy*: proc(
    client: ptr Client;
    resource: ptr Resource;
  ) {.nimcall.}

proc extIdleNotificationV1SendIdled*(resource: ptr Resource) {.inline, exportc: "ext_idle_notification_v1_send_idled".} =
  ## Sends an idled event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(ExtIdleNotificationV1Event_idled.ord)

proc extIdleNotificationV1SendResumed*(resource: ptr Resource) {.inline, exportc: "ext_idle_notification_v1_send_resumed".} =
  ## Sends an resumed event to the client owning the resource.
  ## 
  ## **params**:
  ## * *resource*: The client's resource
  resource.post_event(ExtIdleNotificationV1Event_resumed.ord)

