# Generated by wayland-nim-scanner 1.23.1
{.warning[UnusedImport]:off.}
import wayland/native/common
import wayland/protocols/wayland/code as wayland_code

var pointerConstraintsUnstableV1_types: array[14, ptr Interface]
type ZwpConfinedPointerV1* = object
type ZwpLockedPointerV1* = object
type ZwpPointerConstraintsV1* = object

let
  zwp_pointer_constraints_v1_requests {.exportc.} = [
    Message(name: "destroy", signature: "", types: addr pointer_constraints_unstable_v1_types[0]),
    Message(name: "lock_pointer", signature: "noo?ou", types: addr pointer_constraints_unstable_v1_types[2]),
    Message(name: "confine_pointer", signature: "noo?ou", types: addr pointer_constraints_unstable_v1_types[7]),
  ]

  zwp_pointer_constraints_v1_interface* {.exportc.} = Interface(
    name: "zwp_pointer_constraints_v1",
    version: 1,
    method_count: 3,
    methods: addr zwp_pointer_constraints_v1_requests[0],
  )

  zwp_locked_pointer_v1_requests {.exportc.} = [
    Message(name: "destroy", signature: "", types: addr pointer_constraints_unstable_v1_types[0]),
    Message(name: "set_cursor_position_hint", signature: "ff", types: addr pointer_constraints_unstable_v1_types[0]),
    Message(name: "set_region", signature: "?o", types: addr pointer_constraints_unstable_v1_types[12]),
  ]

  zwp_locked_pointer_v1_events {.exportc.} = [
    Message(name: "locked", signature: "", types: addr pointer_constraints_unstable_v1_types[0]),
    Message(name: "unlocked", signature: "", types: addr pointer_constraints_unstable_v1_types[0]),
  ]

  zwp_locked_pointer_v1_interface* {.exportc.} = Interface(
    name: "zwp_locked_pointer_v1",
    version: 1,
    method_count: 3,
    methods: addr zwp_locked_pointer_v1_requests[0],
    event_count: 2,
    events: addr zwp_locked_pointer_v1_events[0],
  )

  zwp_confined_pointer_v1_requests {.exportc.} = [
    Message(name: "destroy", signature: "", types: addr pointer_constraints_unstable_v1_types[0]),
    Message(name: "set_region", signature: "?o", types: addr pointer_constraints_unstable_v1_types[13]),
  ]

  zwp_confined_pointer_v1_events {.exportc.} = [
    Message(name: "confined", signature: "", types: addr pointer_constraints_unstable_v1_types[0]),
    Message(name: "unconfined", signature: "", types: addr pointer_constraints_unstable_v1_types[0]),
  ]

  zwp_confined_pointer_v1_interface* {.exportc.} = Interface(
    name: "zwp_confined_pointer_v1",
    version: 1,
    method_count: 2,
    methods: addr zwp_confined_pointer_v1_requests[0],
    event_count: 2,
    events: addr zwp_confined_pointer_v1_events[0],
  )


type ZwpPointerConstraintsV1Error* {.size: sizeof(uint32).} = enum
  error_already_constrained = 1
func since*(e: ZwpPointerConstraintsV1Error): int =
  case e
  of error_already_constrained: 1
proc isValid*(e: ZwpPointerConstraintsV1Error; version: int): bool =
  version >= e.since

type ZwpPointerConstraintsV1Lifetime* {.size: sizeof(uint32).} = enum
  lifetime_oneshot = 1
  lifetime_persistent = 2
func since*(e: ZwpPointerConstraintsV1Lifetime): int =
  case e
  of lifetime_oneshot: 1
  of lifetime_persistent: 1
proc isValid*(e: ZwpPointerConstraintsV1Lifetime; version: int): bool =
  version >= e.since

type ZwpPointerConstraintsV1Request* {.size: sizeof(uint32).} = enum
  ZwpPointerConstraintsV1Request_destroy
  ZwpPointerConstraintsV1Request_lock_pointer
  ZwpPointerConstraintsV1Request_confine_pointer
proc since*(e: ZwpPointerConstraintsV1Request): int =
  case e
  of ZwpPointerConstraintsV1Request_destroy: 1
  of ZwpPointerConstraintsV1Request_lock_pointer: 1
  of ZwpPointerConstraintsV1Request_confine_pointer: 1

type ZwpLockedPointerV1Event* {.size: sizeof(uint32).} = enum
  ZwpLockedPointerV1Event_locked
  ZwpLockedPointerV1Event_unlocked
proc since*(e: ZwpLockedPointerV1Event): int =
  case e
  of ZwpLockedPointerV1Event_locked: 1
  of ZwpLockedPointerV1Event_unlocked: 1

type ZwpLockedPointerV1Request* {.size: sizeof(uint32).} = enum
  ZwpLockedPointerV1Request_destroy
  ZwpLockedPointerV1Request_set_cursor_position_hint
  ZwpLockedPointerV1Request_set_region
proc since*(e: ZwpLockedPointerV1Request): int =
  case e
  of ZwpLockedPointerV1Request_destroy: 1
  of ZwpLockedPointerV1Request_set_cursor_position_hint: 1
  of ZwpLockedPointerV1Request_set_region: 1

type ZwpConfinedPointerV1Event* {.size: sizeof(uint32).} = enum
  ZwpConfinedPointerV1Event_confined
  ZwpConfinedPointerV1Event_unconfined
proc since*(e: ZwpConfinedPointerV1Event): int =
  case e
  of ZwpConfinedPointerV1Event_confined: 1
  of ZwpConfinedPointerV1Event_unconfined: 1

type ZwpConfinedPointerV1Request* {.size: sizeof(uint32).} = enum
  ZwpConfinedPointerV1Request_destroy
  ZwpConfinedPointerV1Request_set_region
proc since*(e: ZwpConfinedPointerV1Request): int =
  case e
  of ZwpConfinedPointerV1Request_destroy: 1
  of ZwpConfinedPointerV1Request_set_region: 1

pointerConstraintsUnstableV1_types = [
  nil,
  nil,
  addr zwp_locked_pointer_v1_interface,
  addr wl_surface_interface,
  addr wl_pointer_interface,
  addr wl_region_interface,
  nil,
  addr zwp_confined_pointer_v1_interface,
  addr wl_surface_interface,
  addr wl_pointer_interface,
  addr wl_region_interface,
  nil,
  addr wl_region_interface,
  addr wl_region_interface,
]


