# Generated by wayland-nim-scanner 1.23.1
{.warning[UnusedImport]:off.}
import wayland/native/common
import wayland/protocols/wayland/code as wayland_code

var fractionalScaleV1_types: array[3, ptr Interface]
type WpFractionalScaleManagerV1* = object
type WpFractionalScaleV1* = object

let
  wp_fractional_scale_manager_v1_requests {.exportc.} = [
    Message(name: "destroy", signature: "", types: addr fractional_scale_v1_types[0]),
    Message(name: "get_fractional_scale", signature: "no", types: addr fractional_scale_v1_types[1]),
  ]

  wp_fractional_scale_manager_v1_interface* {.exportc.} = Interface(
    name: "wp_fractional_scale_manager_v1",
    version: 1,
    method_count: 2,
    methods: addr wp_fractional_scale_manager_v1_requests[0],
  )

  wp_fractional_scale_v1_requests {.exportc.} = [
    Message(name: "destroy", signature: "", types: addr fractional_scale_v1_types[0]),
  ]

  wp_fractional_scale_v1_events {.exportc.} = [
    Message(name: "preferred_scale", signature: "u", types: addr fractional_scale_v1_types[0]),
  ]

  wp_fractional_scale_v1_interface* {.exportc.} = Interface(
    name: "wp_fractional_scale_v1",
    version: 1,
    method_count: 1,
    methods: addr wp_fractional_scale_v1_requests[0],
    event_count: 1,
    events: addr wp_fractional_scale_v1_events[0],
  )


type WpFractionalScaleManagerV1Error* {.size: sizeof(uint32).} = enum
  error_fractional_scale_exists = 0
func since*(e: WpFractionalScaleManagerV1Error): int =
  case e
  of error_fractional_scale_exists: 1
proc isValid*(e: WpFractionalScaleManagerV1Error; version: int): bool =
  version >= e.since

type WpFractionalScaleManagerV1Request* {.size: sizeof(uint32).} = enum
  WpFractionalScaleManagerV1Request_destroy
  WpFractionalScaleManagerV1Request_get_fractional_scale
proc since*(e: WpFractionalScaleManagerV1Request): int =
  case e
  of WpFractionalScaleManagerV1Request_destroy: 1
  of WpFractionalScaleManagerV1Request_get_fractional_scale: 1

type WpFractionalScaleV1Event* {.size: sizeof(uint32).} = enum
  WpFractionalScaleV1Event_preferred_scale
proc since*(e: WpFractionalScaleV1Event): int =
  case e
  of WpFractionalScaleV1Event_preferred_scale: 1

type WpFractionalScaleV1Request* {.size: sizeof(uint32).} = enum
  WpFractionalScaleV1Request_destroy
proc since*(e: WpFractionalScaleV1Request): int =
  case e
  of WpFractionalScaleV1Request_destroy: 1

fractionalScaleV1_types = [
  nil,
  addr wp_fractional_scale_v1_interface,
  addr wl_surface_interface,
]


