# Generated by wayland-nim-scanner 1.23.1
{.warning[UnusedImport]:off.}
import wayland/native/server
import wayland/native/common
import wayland/protocols/staging/extForeignToplevelList/v1/server as extForeignToplevelList_server
import code
export code

## The ext_image_capture_source_v1 SERVER protocol
## ###############################################
## 
## Interfaces
## ==========
## 
## * ext_image_capture_source_v1
## * ext_output_image_capture_source_manager_v1
## * ext_foreign_toplevel_image_capture_source_manager_v1
## 
## Copyright
## =========
## 
## Copyright © 2022 Andri Yngvason
## Copyright © 2024 Simon Ser
## 
## Permission is hereby granted, free of charge, to any person obtaining a
## copy of this software and associated documentation files (the "Software"),
## to deal in the Software without restriction, including without limitation
## the rights to use, copy, modify, merge, publish, distribute, sublicense,
## and/or sell copies of the Software, and to permit persons to whom the
## Software is furnished to do so, subject to the following conditions:
## 
## The above copyright notice and this permission notice (including the next
## paragraph) shall be included in all copies or substantial portions of the
## Software.
## 
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
## IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
## FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
## THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
## LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
## FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
## DEALINGS IN THE SOFTWARE.
## 

type ExtImageCaptureSourceV1Interface* = object
  destroy*: proc(
    client: ptr Client;
    resource: ptr Resource;
  ) {.nimcall.}

type ExtOutputImageCaptureSourceManagerV1Interface* = object
  createSource*: proc(
    client: ptr Client;
    resource: ptr Resource;
    source: uint32;
    output: ptr Resource;
  ) {.nimcall.}
  destroy*: proc(
    client: ptr Client;
    resource: ptr Resource;
  ) {.nimcall.}

type ExtForeignToplevelImageCaptureSourceManagerV1Interface* = object
  createSource*: proc(
    client: ptr Client;
    resource: ptr Resource;
    source: uint32;
    toplevelHandle: ptr Resource;
  ) {.nimcall.}
  destroy*: proc(
    client: ptr Client;
    resource: ptr Resource;
  ) {.nimcall.}

