# Generated by wayland-nim-scanner 1.23.1
{.warning[UnusedImport]:off.}
import wayland/native/common
import wayland/protocols/wayland/code as wayland_code

var xwaylandKeyboardGrabUnstableV1_types: array[3, ptr Interface]
type ZwpXwaylandKeyboardGrabManagerV1* = object
type ZwpXwaylandKeyboardGrabV1* = object

let
  zwp_xwayland_keyboard_grab_manager_v1_requests {.exportc.} = [
    Message(name: "destroy", signature: "", types: addr xwayland_keyboard_grab_unstable_v1_types[0]),
    Message(name: "grab_keyboard", signature: "noo", types: addr xwayland_keyboard_grab_unstable_v1_types[0]),
  ]

  zwp_xwayland_keyboard_grab_manager_v1_interface* {.exportc.} = Interface(
    name: "zwp_xwayland_keyboard_grab_manager_v1",
    version: 1,
    method_count: 2,
    methods: addr zwp_xwayland_keyboard_grab_manager_v1_requests[0],
  )

  zwp_xwayland_keyboard_grab_v1_requests {.exportc.} = [
    Message(name: "destroy", signature: "", types: addr xwayland_keyboard_grab_unstable_v1_types[0]),
  ]

  zwp_xwayland_keyboard_grab_v1_interface* {.exportc.} = Interface(
    name: "zwp_xwayland_keyboard_grab_v1",
    version: 1,
    method_count: 1,
    methods: addr zwp_xwayland_keyboard_grab_v1_requests[0],
  )


type ZwpXwaylandKeyboardGrabManagerV1Request* {.size: sizeof(uint32).} = enum
  ZwpXwaylandKeyboardGrabManagerV1Request_destroy
  ZwpXwaylandKeyboardGrabManagerV1Request_grab_keyboard
proc since*(e: ZwpXwaylandKeyboardGrabManagerV1Request): int =
  case e
  of ZwpXwaylandKeyboardGrabManagerV1Request_destroy: 1
  of ZwpXwaylandKeyboardGrabManagerV1Request_grab_keyboard: 1

type ZwpXwaylandKeyboardGrabV1Request* {.size: sizeof(uint32).} = enum
  ZwpXwaylandKeyboardGrabV1Request_destroy
proc since*(e: ZwpXwaylandKeyboardGrabV1Request): int =
  case e
  of ZwpXwaylandKeyboardGrabV1Request_destroy: 1

xwaylandKeyboardGrabUnstableV1_types = [
  addr zwp_xwayland_keyboard_grab_v1_interface,
  addr wl_surface_interface,
  addr wl_seat_interface,
]


