# Generated by wayland-nim-scanner 1.23.1
{.warning[UnusedImport]:off.}
import wayland/native/common
import wayland/protocols/wayland/code as wayland_code
import wayland/protocols/staging/extImageCaptureSource/v1/code as extImageCaptureSource_code

var extImageCopyCaptureV1_types: array[13, ptr Interface]
type ExtImageCopyCaptureCursorSessionV1* = object
type ExtImageCopyCaptureFrameV1* = object
type ExtImageCopyCaptureManagerV1* = object
type ExtImageCopyCaptureSessionV1* = object

let
  ext_image_copy_capture_manager_v1_requests {.exportc.} = [
    Message(name: "create_session", signature: "nou", types: addr ext_image_copy_capture_v1_types[4]),
    Message(name: "create_pointer_cursor_session", signature: "noo", types: addr ext_image_copy_capture_v1_types[7]),
    Message(name: "destroy", signature: "", types: addr ext_image_copy_capture_v1_types[0]),
  ]

  ext_image_copy_capture_manager_v1_interface* {.exportc.} = Interface(
    name: "ext_image_copy_capture_manager_v1",
    version: 1,
    method_count: 3,
    methods: addr ext_image_copy_capture_manager_v1_requests[0],
  )

  ext_image_copy_capture_session_v1_requests {.exportc.} = [
    Message(name: "create_frame", signature: "n", types: addr ext_image_copy_capture_v1_types[10]),
    Message(name: "destroy", signature: "", types: addr ext_image_copy_capture_v1_types[0]),
  ]

  ext_image_copy_capture_session_v1_events {.exportc.} = [
    Message(name: "buffer_size", signature: "uu", types: addr ext_image_copy_capture_v1_types[0]),
    Message(name: "shm_format", signature: "u", types: addr ext_image_copy_capture_v1_types[0]),
    Message(name: "dmabuf_device", signature: "a", types: addr ext_image_copy_capture_v1_types[0]),
    Message(name: "dmabuf_format", signature: "ua", types: addr ext_image_copy_capture_v1_types[0]),
    Message(name: "done", signature: "", types: addr ext_image_copy_capture_v1_types[0]),
    Message(name: "stopped", signature: "", types: addr ext_image_copy_capture_v1_types[0]),
  ]

  ext_image_copy_capture_session_v1_interface* {.exportc.} = Interface(
    name: "ext_image_copy_capture_session_v1",
    version: 1,
    method_count: 2,
    methods: addr ext_image_copy_capture_session_v1_requests[0],
    event_count: 6,
    events: addr ext_image_copy_capture_session_v1_events[0],
  )

  ext_image_copy_capture_frame_v1_requests {.exportc.} = [
    Message(name: "destroy", signature: "", types: addr ext_image_copy_capture_v1_types[0]),
    Message(name: "attach_buffer", signature: "o", types: addr ext_image_copy_capture_v1_types[11]),
    Message(name: "damage_buffer", signature: "iiii", types: addr ext_image_copy_capture_v1_types[0]),
    Message(name: "capture", signature: "", types: addr ext_image_copy_capture_v1_types[0]),
  ]

  ext_image_copy_capture_frame_v1_events {.exportc.} = [
    Message(name: "transform", signature: "u", types: addr ext_image_copy_capture_v1_types[0]),
    Message(name: "damage", signature: "iiii", types: addr ext_image_copy_capture_v1_types[0]),
    Message(name: "presentation_time", signature: "uuu", types: addr ext_image_copy_capture_v1_types[0]),
    Message(name: "ready", signature: "", types: addr ext_image_copy_capture_v1_types[0]),
    Message(name: "failed", signature: "u", types: addr ext_image_copy_capture_v1_types[0]),
  ]

  ext_image_copy_capture_frame_v1_interface* {.exportc.} = Interface(
    name: "ext_image_copy_capture_frame_v1",
    version: 1,
    method_count: 4,
    methods: addr ext_image_copy_capture_frame_v1_requests[0],
    event_count: 5,
    events: addr ext_image_copy_capture_frame_v1_events[0],
  )

  ext_image_copy_capture_cursor_session_v1_requests {.exportc.} = [
    Message(name: "destroy", signature: "", types: addr ext_image_copy_capture_v1_types[0]),
    Message(name: "get_capture_session", signature: "n", types: addr ext_image_copy_capture_v1_types[12]),
  ]

  ext_image_copy_capture_cursor_session_v1_events {.exportc.} = [
    Message(name: "enter", signature: "", types: addr ext_image_copy_capture_v1_types[0]),
    Message(name: "leave", signature: "", types: addr ext_image_copy_capture_v1_types[0]),
    Message(name: "position", signature: "ii", types: addr ext_image_copy_capture_v1_types[0]),
    Message(name: "hotspot", signature: "ii", types: addr ext_image_copy_capture_v1_types[0]),
  ]

  ext_image_copy_capture_cursor_session_v1_interface* {.exportc.} = Interface(
    name: "ext_image_copy_capture_cursor_session_v1",
    version: 1,
    method_count: 2,
    methods: addr ext_image_copy_capture_cursor_session_v1_requests[0],
    event_count: 4,
    events: addr ext_image_copy_capture_cursor_session_v1_events[0],
  )


type ExtImageCopyCaptureManagerV1Error* {.size: sizeof(uint32).} = enum
  error_invalid_option = 1
func since*(e: ExtImageCopyCaptureManagerV1Error): int =
  case e
  of error_invalid_option: 1
proc isValid*(e: ExtImageCopyCaptureManagerV1Error; version: int): bool =
  version >= e.since

type ExtImageCopyCaptureManagerV1Options* {.size: sizeof(uint32).} = enum
  options_paint_cursors = 1
func since*(e: ExtImageCopyCaptureManagerV1Options): int =
  case e
  of options_paint_cursors: 1
proc isValid*(e: ExtImageCopyCaptureManagerV1Options; version: int): bool =
  version >= e.since

type ExtImageCopyCaptureSessionV1Error* {.size: sizeof(uint32).} = enum
  error_duplicate_frame = 1
func since*(e: ExtImageCopyCaptureSessionV1Error): int =
  case e
  of error_duplicate_frame: 1
proc isValid*(e: ExtImageCopyCaptureSessionV1Error; version: int): bool =
  version >= e.since

type ExtImageCopyCaptureFrameV1Error* {.size: sizeof(uint32).} = enum
  error_no_buffer = 1
  error_invalid_buffer_damage = 2
  error_already_captured = 3
func since*(e: ExtImageCopyCaptureFrameV1Error): int =
  case e
  of error_no_buffer: 1
  of error_invalid_buffer_damage: 1
  of error_already_captured: 1
proc isValid*(e: ExtImageCopyCaptureFrameV1Error; version: int): bool =
  version >= e.since

type ExtImageCopyCaptureFrameV1FailureReason* {.size: sizeof(uint32).} = enum
  failure_reason_unknown = 0
  failure_reason_buffer_constraints = 1
  failure_reason_stopped = 2
func since*(e: ExtImageCopyCaptureFrameV1FailureReason): int =
  case e
  of failure_reason_unknown: 1
  of failure_reason_buffer_constraints: 1
  of failure_reason_stopped: 1
proc isValid*(e: ExtImageCopyCaptureFrameV1FailureReason; version: int): bool =
  version >= e.since

type ExtImageCopyCaptureCursorSessionV1Error* {.size: sizeof(uint32).} = enum
  error_duplicate_session = 1
func since*(e: ExtImageCopyCaptureCursorSessionV1Error): int =
  case e
  of error_duplicate_session: 1
proc isValid*(e: ExtImageCopyCaptureCursorSessionV1Error; version: int): bool =
  version >= e.since

type ExtImageCopyCaptureManagerV1Request* {.size: sizeof(uint32).} = enum
  ExtImageCopyCaptureManagerV1Request_create_session
  ExtImageCopyCaptureManagerV1Request_create_pointer_cursor_session
  ExtImageCopyCaptureManagerV1Request_destroy
proc since*(e: ExtImageCopyCaptureManagerV1Request): int =
  case e
  of ExtImageCopyCaptureManagerV1Request_create_session: 1
  of ExtImageCopyCaptureManagerV1Request_create_pointer_cursor_session: 1
  of ExtImageCopyCaptureManagerV1Request_destroy: 1

type ExtImageCopyCaptureSessionV1Event* {.size: sizeof(uint32).} = enum
  ExtImageCopyCaptureSessionV1Event_buffer_size
  ExtImageCopyCaptureSessionV1Event_shm_format
  ExtImageCopyCaptureSessionV1Event_dmabuf_device
  ExtImageCopyCaptureSessionV1Event_dmabuf_format
  ExtImageCopyCaptureSessionV1Event_done
  ExtImageCopyCaptureSessionV1Event_stopped
proc since*(e: ExtImageCopyCaptureSessionV1Event): int =
  case e
  of ExtImageCopyCaptureSessionV1Event_buffer_size: 1
  of ExtImageCopyCaptureSessionV1Event_shm_format: 1
  of ExtImageCopyCaptureSessionV1Event_dmabuf_device: 1
  of ExtImageCopyCaptureSessionV1Event_dmabuf_format: 1
  of ExtImageCopyCaptureSessionV1Event_done: 1
  of ExtImageCopyCaptureSessionV1Event_stopped: 1

type ExtImageCopyCaptureSessionV1Request* {.size: sizeof(uint32).} = enum
  ExtImageCopyCaptureSessionV1Request_create_frame
  ExtImageCopyCaptureSessionV1Request_destroy
proc since*(e: ExtImageCopyCaptureSessionV1Request): int =
  case e
  of ExtImageCopyCaptureSessionV1Request_create_frame: 1
  of ExtImageCopyCaptureSessionV1Request_destroy: 1

type ExtImageCopyCaptureFrameV1Event* {.size: sizeof(uint32).} = enum
  ExtImageCopyCaptureFrameV1Event_transform
  ExtImageCopyCaptureFrameV1Event_damage
  ExtImageCopyCaptureFrameV1Event_presentation_time
  ExtImageCopyCaptureFrameV1Event_ready
  ExtImageCopyCaptureFrameV1Event_failed
proc since*(e: ExtImageCopyCaptureFrameV1Event): int =
  case e
  of ExtImageCopyCaptureFrameV1Event_transform: 1
  of ExtImageCopyCaptureFrameV1Event_damage: 1
  of ExtImageCopyCaptureFrameV1Event_presentation_time: 1
  of ExtImageCopyCaptureFrameV1Event_ready: 1
  of ExtImageCopyCaptureFrameV1Event_failed: 1

type ExtImageCopyCaptureFrameV1Request* {.size: sizeof(uint32).} = enum
  ExtImageCopyCaptureFrameV1Request_destroy
  ExtImageCopyCaptureFrameV1Request_attach_buffer
  ExtImageCopyCaptureFrameV1Request_damage_buffer
  ExtImageCopyCaptureFrameV1Request_capture
proc since*(e: ExtImageCopyCaptureFrameV1Request): int =
  case e
  of ExtImageCopyCaptureFrameV1Request_destroy: 1
  of ExtImageCopyCaptureFrameV1Request_attach_buffer: 1
  of ExtImageCopyCaptureFrameV1Request_damage_buffer: 1
  of ExtImageCopyCaptureFrameV1Request_capture: 1

type ExtImageCopyCaptureCursorSessionV1Event* {.size: sizeof(uint32).} = enum
  ExtImageCopyCaptureCursorSessionV1Event_enter
  ExtImageCopyCaptureCursorSessionV1Event_leave
  ExtImageCopyCaptureCursorSessionV1Event_position
  ExtImageCopyCaptureCursorSessionV1Event_hotspot
proc since*(e: ExtImageCopyCaptureCursorSessionV1Event): int =
  case e
  of ExtImageCopyCaptureCursorSessionV1Event_enter: 1
  of ExtImageCopyCaptureCursorSessionV1Event_leave: 1
  of ExtImageCopyCaptureCursorSessionV1Event_position: 1
  of ExtImageCopyCaptureCursorSessionV1Event_hotspot: 1

type ExtImageCopyCaptureCursorSessionV1Request* {.size: sizeof(uint32).} = enum
  ExtImageCopyCaptureCursorSessionV1Request_destroy
  ExtImageCopyCaptureCursorSessionV1Request_get_capture_session
proc since*(e: ExtImageCopyCaptureCursorSessionV1Request): int =
  case e
  of ExtImageCopyCaptureCursorSessionV1Request_destroy: 1
  of ExtImageCopyCaptureCursorSessionV1Request_get_capture_session: 1

extImageCopyCaptureV1_types = [
  nil,
  nil,
  nil,
  nil,
  addr ext_image_copy_capture_session_v1_interface,
  addr ext_image_capture_source_v1_interface,
  nil,
  addr ext_image_copy_capture_cursor_session_v1_interface,
  addr ext_image_capture_source_v1_interface,
  addr wl_pointer_interface,
  addr ext_image_copy_capture_frame_v1_interface,
  addr wl_buffer_interface,
  addr ext_image_copy_capture_session_v1_interface,
]


