# Generated by wayland-nim-scanner 1.23.1
{.warning[UnusedImport]:off.}
import wayland/native/common
import wayland/protocols/wayland/code as wayland_code
import wayland/protocols/stable/xdgShell/code as xdgShell_code

var xdgToplevelIconV1_types: array[6, ptr Interface]
type XdgToplevelIconManagerV1* = object
type XdgToplevelIconV1* = object

let
  xdg_toplevel_icon_manager_v1_requests {.exportc.} = [
    Message(name: "destroy", signature: "", types: addr xdg_toplevel_icon_v1_types[0]),
    Message(name: "create_icon", signature: "n", types: addr xdg_toplevel_icon_v1_types[1]),
    Message(name: "set_icon", signature: "o?o", types: addr xdg_toplevel_icon_v1_types[2]),
  ]

  xdg_toplevel_icon_manager_v1_events {.exportc.} = [
    Message(name: "icon_size", signature: "i", types: addr xdg_toplevel_icon_v1_types[0]),
    Message(name: "done", signature: "", types: addr xdg_toplevel_icon_v1_types[0]),
  ]

  xdg_toplevel_icon_manager_v1_interface* {.exportc.} = Interface(
    name: "xdg_toplevel_icon_manager_v1",
    version: 1,
    method_count: 3,
    methods: addr xdg_toplevel_icon_manager_v1_requests[0],
    event_count: 2,
    events: addr xdg_toplevel_icon_manager_v1_events[0],
  )

  xdg_toplevel_icon_v1_requests {.exportc.} = [
    Message(name: "destroy", signature: "", types: addr xdg_toplevel_icon_v1_types[0]),
    Message(name: "set_name", signature: "s", types: addr xdg_toplevel_icon_v1_types[0]),
    Message(name: "add_buffer", signature: "oi", types: addr xdg_toplevel_icon_v1_types[4]),
  ]

  xdg_toplevel_icon_v1_interface* {.exportc.} = Interface(
    name: "xdg_toplevel_icon_v1",
    version: 1,
    method_count: 3,
    methods: addr xdg_toplevel_icon_v1_requests[0],
  )


type XdgToplevelIconV1Error* {.size: sizeof(uint32).} = enum
  error_invalid_buffer = 1
  error_immutable = 2
  error_no_buffer = 3
func since*(e: XdgToplevelIconV1Error): int =
  case e
  of error_invalid_buffer: 1
  of error_immutable: 1
  of error_no_buffer: 1
proc isValid*(e: XdgToplevelIconV1Error; version: int): bool =
  version >= e.since

type XdgToplevelIconManagerV1Event* {.size: sizeof(uint32).} = enum
  XdgToplevelIconManagerV1Event_icon_size
  XdgToplevelIconManagerV1Event_done
proc since*(e: XdgToplevelIconManagerV1Event): int =
  case e
  of XdgToplevelIconManagerV1Event_icon_size: 1
  of XdgToplevelIconManagerV1Event_done: 1

type XdgToplevelIconManagerV1Request* {.size: sizeof(uint32).} = enum
  XdgToplevelIconManagerV1Request_destroy
  XdgToplevelIconManagerV1Request_create_icon
  XdgToplevelIconManagerV1Request_set_icon
proc since*(e: XdgToplevelIconManagerV1Request): int =
  case e
  of XdgToplevelIconManagerV1Request_destroy: 1
  of XdgToplevelIconManagerV1Request_create_icon: 1
  of XdgToplevelIconManagerV1Request_set_icon: 1

type XdgToplevelIconV1Request* {.size: sizeof(uint32).} = enum
  XdgToplevelIconV1Request_destroy
  XdgToplevelIconV1Request_set_name
  XdgToplevelIconV1Request_add_buffer
proc since*(e: XdgToplevelIconV1Request): int =
  case e
  of XdgToplevelIconV1Request_destroy: 1
  of XdgToplevelIconV1Request_set_name: 1
  of XdgToplevelIconV1Request_add_buffer: 1

xdgToplevelIconV1_types = [
  nil,
  addr xdg_toplevel_icon_v1_interface,
  addr xdg_toplevel_interface,
  addr xdg_toplevel_icon_v1_interface,
  addr wl_buffer_interface,
  nil,
]


