# Generated by wayland-nim-scanner 1.23.1
{.warning[UnusedImport]:off.}
import wayland/native/common
import wayland/protocols/wayland/code as wayland_code

var extDataControlV1_types: array[10, ptr Interface]
type ExtDataControlDeviceV1* = object
type ExtDataControlManagerV1* = object
type ExtDataControlOfferV1* = object
type ExtDataControlSourceV1* = object

let
  ext_data_control_manager_v1_requests {.exportc.} = [
    Message(name: "create_data_source", signature: "n", types: addr ext_data_control_v1_types[2]),
    Message(name: "get_data_device", signature: "no", types: addr ext_data_control_v1_types[3]),
    Message(name: "destroy", signature: "", types: addr ext_data_control_v1_types[0]),
  ]

  ext_data_control_manager_v1_interface* {.exportc.} = Interface(
    name: "ext_data_control_manager_v1",
    version: 1,
    method_count: 3,
    methods: addr ext_data_control_manager_v1_requests[0],
  )

  ext_data_control_device_v1_requests {.exportc.} = [
    Message(name: "set_selection", signature: "?o", types: addr ext_data_control_v1_types[5]),
    Message(name: "destroy", signature: "", types: addr ext_data_control_v1_types[0]),
    Message(name: "set_primary_selection", signature: "?o", types: addr ext_data_control_v1_types[6]),
  ]

  ext_data_control_device_v1_events {.exportc.} = [
    Message(name: "data_offer", signature: "n", types: addr ext_data_control_v1_types[7]),
    Message(name: "selection", signature: "?o", types: addr ext_data_control_v1_types[8]),
    Message(name: "finished", signature: "", types: addr ext_data_control_v1_types[0]),
    Message(name: "primary_selection", signature: "?o", types: addr ext_data_control_v1_types[9]),
  ]

  ext_data_control_device_v1_interface* {.exportc.} = Interface(
    name: "ext_data_control_device_v1",
    version: 1,
    method_count: 3,
    methods: addr ext_data_control_device_v1_requests[0],
    event_count: 4,
    events: addr ext_data_control_device_v1_events[0],
  )

  ext_data_control_source_v1_requests {.exportc.} = [
    Message(name: "offer", signature: "s", types: addr ext_data_control_v1_types[0]),
    Message(name: "destroy", signature: "", types: addr ext_data_control_v1_types[0]),
  ]

  ext_data_control_source_v1_events {.exportc.} = [
    Message(name: "send", signature: "sh", types: addr ext_data_control_v1_types[0]),
    Message(name: "cancelled", signature: "", types: addr ext_data_control_v1_types[0]),
  ]

  ext_data_control_source_v1_interface* {.exportc.} = Interface(
    name: "ext_data_control_source_v1",
    version: 1,
    method_count: 2,
    methods: addr ext_data_control_source_v1_requests[0],
    event_count: 2,
    events: addr ext_data_control_source_v1_events[0],
  )

  ext_data_control_offer_v1_requests {.exportc.} = [
    Message(name: "receive", signature: "sh", types: addr ext_data_control_v1_types[0]),
    Message(name: "destroy", signature: "", types: addr ext_data_control_v1_types[0]),
  ]

  ext_data_control_offer_v1_events {.exportc.} = [
    Message(name: "offer", signature: "s", types: addr ext_data_control_v1_types[0]),
  ]

  ext_data_control_offer_v1_interface* {.exportc.} = Interface(
    name: "ext_data_control_offer_v1",
    version: 1,
    method_count: 2,
    methods: addr ext_data_control_offer_v1_requests[0],
    event_count: 1,
    events: addr ext_data_control_offer_v1_events[0],
  )


type ExtDataControlDeviceV1Error* {.size: sizeof(uint32).} = enum
  error_used_source = 1
func since*(e: ExtDataControlDeviceV1Error): int =
  case e
  of error_used_source: 1
proc isValid*(e: ExtDataControlDeviceV1Error; version: int): bool =
  version >= e.since

type ExtDataControlSourceV1Error* {.size: sizeof(uint32).} = enum
  error_invalid_offer = 1
func since*(e: ExtDataControlSourceV1Error): int =
  case e
  of error_invalid_offer: 1
proc isValid*(e: ExtDataControlSourceV1Error; version: int): bool =
  version >= e.since

type ExtDataControlManagerV1Request* {.size: sizeof(uint32).} = enum
  ExtDataControlManagerV1Request_create_data_source
  ExtDataControlManagerV1Request_get_data_device
  ExtDataControlManagerV1Request_destroy
proc since*(e: ExtDataControlManagerV1Request): int =
  case e
  of ExtDataControlManagerV1Request_create_data_source: 1
  of ExtDataControlManagerV1Request_get_data_device: 1
  of ExtDataControlManagerV1Request_destroy: 1

type ExtDataControlDeviceV1Event* {.size: sizeof(uint32).} = enum
  ExtDataControlDeviceV1Event_data_offer
  ExtDataControlDeviceV1Event_selection
  ExtDataControlDeviceV1Event_finished
  ExtDataControlDeviceV1Event_primary_selection
proc since*(e: ExtDataControlDeviceV1Event): int =
  case e
  of ExtDataControlDeviceV1Event_data_offer: 1
  of ExtDataControlDeviceV1Event_selection: 1
  of ExtDataControlDeviceV1Event_finished: 1
  of ExtDataControlDeviceV1Event_primary_selection: 1

type ExtDataControlDeviceV1Request* {.size: sizeof(uint32).} = enum
  ExtDataControlDeviceV1Request_set_selection
  ExtDataControlDeviceV1Request_destroy
  ExtDataControlDeviceV1Request_set_primary_selection
proc since*(e: ExtDataControlDeviceV1Request): int =
  case e
  of ExtDataControlDeviceV1Request_set_selection: 1
  of ExtDataControlDeviceV1Request_destroy: 1
  of ExtDataControlDeviceV1Request_set_primary_selection: 1

type ExtDataControlSourceV1Event* {.size: sizeof(uint32).} = enum
  ExtDataControlSourceV1Event_send
  ExtDataControlSourceV1Event_cancelled
proc since*(e: ExtDataControlSourceV1Event): int =
  case e
  of ExtDataControlSourceV1Event_send: 1
  of ExtDataControlSourceV1Event_cancelled: 1

type ExtDataControlSourceV1Request* {.size: sizeof(uint32).} = enum
  ExtDataControlSourceV1Request_offer
  ExtDataControlSourceV1Request_destroy
proc since*(e: ExtDataControlSourceV1Request): int =
  case e
  of ExtDataControlSourceV1Request_offer: 1
  of ExtDataControlSourceV1Request_destroy: 1

type ExtDataControlOfferV1Event* {.size: sizeof(uint32).} = enum
  ExtDataControlOfferV1Event_offer
proc since*(e: ExtDataControlOfferV1Event): int =
  case e
  of ExtDataControlOfferV1Event_offer: 1

type ExtDataControlOfferV1Request* {.size: sizeof(uint32).} = enum
  ExtDataControlOfferV1Request_receive
  ExtDataControlOfferV1Request_destroy
proc since*(e: ExtDataControlOfferV1Request): int =
  case e
  of ExtDataControlOfferV1Request_receive: 1
  of ExtDataControlOfferV1Request_destroy: 1

extDataControlV1_types = [
  nil,
  nil,
  addr ext_data_control_source_v1_interface,
  addr ext_data_control_device_v1_interface,
  addr wl_seat_interface,
  addr ext_data_control_source_v1_interface,
  addr ext_data_control_source_v1_interface,
  addr ext_data_control_offer_v1_interface,
  addr ext_data_control_offer_v1_interface,
  addr ext_data_control_offer_v1_interface,
]


