# Generated by wayland-nim-scanner 1.23.1
import common

var wayland_types: array[95, ptr wl_interface]
let
  wl_display_requests {.exportc.} = [
    wl_message(name: "sync", signature: "n", types: addr wayland_types[8]),
    wl_message(name: "get_registry", signature: "n", types: addr wayland_types[9]),
  ]

  wl_display_events {.exportc.} = [
    wl_message(name: "error", signature: "ous", types: addr wayland_types[0]),
    wl_message(name: "delete_id", signature: "u", types: addr wayland_types[0]),
  ]

  wl_display_interface* {.exportc.} = wl_interface(
    name: "wl_display",
    version: 1,
    method_count: 2,
    methods: addr wl_display_requests[0],
    event_count: 2,
    events: addr wl_display_events[0],
  )

  wl_registry_requests {.exportc.} = [
    wl_message(name: "bind", signature: "usun", types: addr wayland_types[0]),
  ]

  wl_registry_events {.exportc.} = [
    wl_message(name: "global", signature: "usu", types: addr wayland_types[0]),
    wl_message(name: "global_remove", signature: "u", types: addr wayland_types[0]),
  ]

  wl_registry_interface* {.exportc.} = wl_interface(
    name: "wl_registry",
    version: 1,
    method_count: 1,
    methods: addr wl_registry_requests[0],
    event_count: 2,
    events: addr wl_registry_events[0],
  )

  wl_callback_events {.exportc.} = [
    wl_message(name: "done", signature: "u", types: addr wayland_types[0]),
  ]

  wl_callback_interface* {.exportc.} = wl_interface(
    name: "wl_callback",
    version: 1,
    event_count: 1,
    events: addr wl_callback_events[0],
  )

  wl_compositor_requests {.exportc.} = [
    wl_message(name: "create_surface", signature: "n", types: addr wayland_types[10]),
    wl_message(name: "create_region", signature: "n", types: addr wayland_types[11]),
  ]

  wl_compositor_interface* {.exportc.} = wl_interface(
    name: "wl_compositor",
    version: 6,
    method_count: 2,
    methods: addr wl_compositor_requests[0],
  )

  wl_shm_pool_requests {.exportc.} = [
    wl_message(name: "create_buffer", signature: "niiiiu", types: addr wayland_types[12]),
    wl_message(name: "destroy", signature: "", types: addr wayland_types[0]),
    wl_message(name: "resize", signature: "i", types: addr wayland_types[0]),
  ]

  wl_shm_pool_interface* {.exportc.} = wl_interface(
    name: "wl_shm_pool",
    version: 2,
    method_count: 3,
    methods: addr wl_shm_pool_requests[0],
  )

  wl_shm_requests {.exportc.} = [
    wl_message(name: "create_pool", signature: "nhi", types: addr wayland_types[18]),
    wl_message(name: "release", signature: "2", types: addr wayland_types[0]),
  ]

  wl_shm_events {.exportc.} = [
    wl_message(name: "format", signature: "u", types: addr wayland_types[0]),
  ]

  wl_shm_interface* {.exportc.} = wl_interface(
    name: "wl_shm",
    version: 2,
    method_count: 2,
    methods: addr wl_shm_requests[0],
    event_count: 1,
    events: addr wl_shm_events[0],
  )

  wl_buffer_requests {.exportc.} = [
    wl_message(name: "destroy", signature: "", types: addr wayland_types[0]),
  ]

  wl_buffer_events {.exportc.} = [
    wl_message(name: "release", signature: "", types: addr wayland_types[0]),
  ]

  wl_buffer_interface* {.exportc.} = wl_interface(
    name: "wl_buffer",
    version: 1,
    method_count: 1,
    methods: addr wl_buffer_requests[0],
    event_count: 1,
    events: addr wl_buffer_events[0],
  )

  wl_data_offer_requests {.exportc.} = [
    wl_message(name: "accept", signature: "u?s", types: addr wayland_types[0]),
    wl_message(name: "receive", signature: "sh", types: addr wayland_types[0]),
    wl_message(name: "destroy", signature: "", types: addr wayland_types[0]),
    wl_message(name: "finish", signature: "3", types: addr wayland_types[0]),
    wl_message(name: "set_actions", signature: "3uu", types: addr wayland_types[0]),
  ]

  wl_data_offer_events {.exportc.} = [
    wl_message(name: "offer", signature: "s", types: addr wayland_types[0]),
    wl_message(name: "source_actions", signature: "3u", types: addr wayland_types[0]),
    wl_message(name: "action", signature: "3u", types: addr wayland_types[0]),
  ]

  wl_data_offer_interface* {.exportc.} = wl_interface(
    name: "wl_data_offer",
    version: 3,
    method_count: 5,
    methods: addr wl_data_offer_requests[0],
    event_count: 3,
    events: addr wl_data_offer_events[0],
  )

  wl_data_source_requests {.exportc.} = [
    wl_message(name: "offer", signature: "s", types: addr wayland_types[0]),
    wl_message(name: "destroy", signature: "", types: addr wayland_types[0]),
    wl_message(name: "set_actions", signature: "3u", types: addr wayland_types[0]),
  ]

  wl_data_source_events {.exportc.} = [
    wl_message(name: "target", signature: "?s", types: addr wayland_types[0]),
    wl_message(name: "send", signature: "sh", types: addr wayland_types[0]),
    wl_message(name: "cancelled", signature: "", types: addr wayland_types[0]),
    wl_message(name: "dnd_drop_performed", signature: "3", types: addr wayland_types[0]),
    wl_message(name: "dnd_finished", signature: "3", types: addr wayland_types[0]),
    wl_message(name: "action", signature: "3u", types: addr wayland_types[0]),
  ]

  wl_data_source_interface* {.exportc.} = wl_interface(
    name: "wl_data_source",
    version: 3,
    method_count: 3,
    methods: addr wl_data_source_requests[0],
    event_count: 6,
    events: addr wl_data_source_events[0],
  )

  wl_data_device_requests {.exportc.} = [
    wl_message(name: "start_drag", signature: "?oo?ou", types: addr wayland_types[21]),
    wl_message(name: "set_selection", signature: "?ou", types: addr wayland_types[25]),
    wl_message(name: "release", signature: "2", types: addr wayland_types[0]),
  ]

  wl_data_device_events {.exportc.} = [
    wl_message(name: "data_offer", signature: "n", types: addr wayland_types[27]),
    wl_message(name: "enter", signature: "uoff?o", types: addr wayland_types[28]),
    wl_message(name: "leave", signature: "", types: addr wayland_types[0]),
    wl_message(name: "motion", signature: "uff", types: addr wayland_types[0]),
    wl_message(name: "drop", signature: "", types: addr wayland_types[0]),
    wl_message(name: "selection", signature: "?o", types: addr wayland_types[33]),
  ]

  wl_data_device_interface* {.exportc.} = wl_interface(
    name: "wl_data_device",
    version: 3,
    method_count: 3,
    methods: addr wl_data_device_requests[0],
    event_count: 6,
    events: addr wl_data_device_events[0],
  )

  wl_data_device_manager_requests {.exportc.} = [
    wl_message(name: "create_data_source", signature: "n", types: addr wayland_types[34]),
    wl_message(name: "get_data_device", signature: "no", types: addr wayland_types[35]),
  ]

  wl_data_device_manager_interface* {.exportc.} = wl_interface(
    name: "wl_data_device_manager",
    version: 3,
    method_count: 2,
    methods: addr wl_data_device_manager_requests[0],
  )

  wl_shell_requests {.exportc.} = [
    wl_message(name: "get_shell_surface", signature: "no", types: addr wayland_types[37]),
  ]

  wl_shell_interface* {.exportc.} = wl_interface(
    name: "wl_shell",
    version: 1,
    method_count: 1,
    methods: addr wl_shell_requests[0],
  )

  wl_shell_surface_requests {.exportc.} = [
    wl_message(name: "pong", signature: "u", types: addr wayland_types[0]),
    wl_message(name: "move", signature: "ou", types: addr wayland_types[39]),
    wl_message(name: "resize", signature: "ouu", types: addr wayland_types[41]),
    wl_message(name: "set_toplevel", signature: "", types: addr wayland_types[0]),
    wl_message(name: "set_transient", signature: "oiiu", types: addr wayland_types[44]),
    wl_message(name: "set_fullscreen", signature: "uu?o", types: addr wayland_types[48]),
    wl_message(name: "set_popup", signature: "ouoiiu", types: addr wayland_types[51]),
    wl_message(name: "set_maximized", signature: "?o", types: addr wayland_types[57]),
    wl_message(name: "set_title", signature: "s", types: addr wayland_types[0]),
    wl_message(name: "set_class", signature: "s", types: addr wayland_types[0]),
  ]

  wl_shell_surface_events {.exportc.} = [
    wl_message(name: "ping", signature: "u", types: addr wayland_types[0]),
    wl_message(name: "configure", signature: "uii", types: addr wayland_types[0]),
    wl_message(name: "popup_done", signature: "", types: addr wayland_types[0]),
  ]

  wl_shell_surface_interface* {.exportc.} = wl_interface(
    name: "wl_shell_surface",
    version: 1,
    method_count: 10,
    methods: addr wl_shell_surface_requests[0],
    event_count: 3,
    events: addr wl_shell_surface_events[0],
  )

  wl_surface_requests {.exportc.} = [
    wl_message(name: "destroy", signature: "", types: addr wayland_types[0]),
    wl_message(name: "attach", signature: "?oii", types: addr wayland_types[58]),
    wl_message(name: "damage", signature: "iiii", types: addr wayland_types[0]),
    wl_message(name: "frame", signature: "n", types: addr wayland_types[61]),
    wl_message(name: "set_opaque_region", signature: "?o", types: addr wayland_types[62]),
    wl_message(name: "set_input_region", signature: "?o", types: addr wayland_types[63]),
    wl_message(name: "commit", signature: "", types: addr wayland_types[0]),
    wl_message(name: "set_buffer_transform", signature: "2i", types: addr wayland_types[0]),
    wl_message(name: "set_buffer_scale", signature: "3i", types: addr wayland_types[0]),
    wl_message(name: "damage_buffer", signature: "4iiii", types: addr wayland_types[0]),
    wl_message(name: "offset", signature: "5ii", types: addr wayland_types[0]),
  ]

  wl_surface_events {.exportc.} = [
    wl_message(name: "enter", signature: "o", types: addr wayland_types[64]),
    wl_message(name: "leave", signature: "o", types: addr wayland_types[65]),
    wl_message(name: "preferred_buffer_scale", signature: "6i", types: addr wayland_types[0]),
    wl_message(name: "preferred_buffer_transform", signature: "6u", types: addr wayland_types[0]),
  ]

  wl_surface_interface* {.exportc.} = wl_interface(
    name: "wl_surface",
    version: 6,
    method_count: 11,
    methods: addr wl_surface_requests[0],
    event_count: 4,
    events: addr wl_surface_events[0],
  )

  wl_seat_requests {.exportc.} = [
    wl_message(name: "get_pointer", signature: "n", types: addr wayland_types[66]),
    wl_message(name: "get_keyboard", signature: "n", types: addr wayland_types[67]),
    wl_message(name: "get_touch", signature: "n", types: addr wayland_types[68]),
    wl_message(name: "release", signature: "5", types: addr wayland_types[0]),
  ]

  wl_seat_events {.exportc.} = [
    wl_message(name: "capabilities", signature: "u", types: addr wayland_types[0]),
    wl_message(name: "name", signature: "2s", types: addr wayland_types[0]),
  ]

  wl_seat_interface* {.exportc.} = wl_interface(
    name: "wl_seat",
    version: 9,
    method_count: 4,
    methods: addr wl_seat_requests[0],
    event_count: 2,
    events: addr wl_seat_events[0],
  )

  wl_pointer_requests {.exportc.} = [
    wl_message(name: "set_cursor", signature: "u?oii", types: addr wayland_types[69]),
    wl_message(name: "release", signature: "3", types: addr wayland_types[0]),
  ]

  wl_pointer_events {.exportc.} = [
    wl_message(name: "enter", signature: "uoff", types: addr wayland_types[73]),
    wl_message(name: "leave", signature: "uo", types: addr wayland_types[77]),
    wl_message(name: "motion", signature: "uff", types: addr wayland_types[0]),
    wl_message(name: "button", signature: "uuuu", types: addr wayland_types[0]),
    wl_message(name: "axis", signature: "uuf", types: addr wayland_types[0]),
    wl_message(name: "frame", signature: "5", types: addr wayland_types[0]),
    wl_message(name: "axis_source", signature: "5u", types: addr wayland_types[0]),
    wl_message(name: "axis_stop", signature: "5uu", types: addr wayland_types[0]),
    wl_message(name: "axis_discrete", signature: "5ui", types: addr wayland_types[0]),
    wl_message(name: "axis_value120", signature: "8ui", types: addr wayland_types[0]),
    wl_message(name: "axis_relative_direction", signature: "9uu", types: addr wayland_types[0]),
  ]

  wl_pointer_interface* {.exportc.} = wl_interface(
    name: "wl_pointer",
    version: 9,
    method_count: 2,
    methods: addr wl_pointer_requests[0],
    event_count: 11,
    events: addr wl_pointer_events[0],
  )

  wl_keyboard_requests {.exportc.} = [
    wl_message(name: "release", signature: "3", types: addr wayland_types[0]),
  ]

  wl_keyboard_events {.exportc.} = [
    wl_message(name: "keymap", signature: "uhu", types: addr wayland_types[0]),
    wl_message(name: "enter", signature: "uoa", types: addr wayland_types[79]),
    wl_message(name: "leave", signature: "uo", types: addr wayland_types[82]),
    wl_message(name: "key", signature: "uuuu", types: addr wayland_types[0]),
    wl_message(name: "modifiers", signature: "uuuuu", types: addr wayland_types[0]),
    wl_message(name: "repeat_info", signature: "4ii", types: addr wayland_types[0]),
  ]

  wl_keyboard_interface* {.exportc.} = wl_interface(
    name: "wl_keyboard",
    version: 9,
    method_count: 1,
    methods: addr wl_keyboard_requests[0],
    event_count: 6,
    events: addr wl_keyboard_events[0],
  )

  wl_touch_requests {.exportc.} = [
    wl_message(name: "release", signature: "3", types: addr wayland_types[0]),
  ]

  wl_touch_events {.exportc.} = [
    wl_message(name: "down", signature: "uuoiff", types: addr wayland_types[84]),
    wl_message(name: "up", signature: "uui", types: addr wayland_types[0]),
    wl_message(name: "motion", signature: "uiff", types: addr wayland_types[0]),
    wl_message(name: "frame", signature: "", types: addr wayland_types[0]),
    wl_message(name: "cancel", signature: "", types: addr wayland_types[0]),
    wl_message(name: "shape", signature: "6iff", types: addr wayland_types[0]),
    wl_message(name: "orientation", signature: "6if", types: addr wayland_types[0]),
  ]

  wl_touch_interface* {.exportc.} = wl_interface(
    name: "wl_touch",
    version: 9,
    method_count: 1,
    methods: addr wl_touch_requests[0],
    event_count: 7,
    events: addr wl_touch_events[0],
  )

  wl_output_requests {.exportc.} = [
    wl_message(name: "release", signature: "3", types: addr wayland_types[0]),
  ]

  wl_output_events {.exportc.} = [
    wl_message(name: "geometry", signature: "iiiiissi", types: addr wayland_types[0]),
    wl_message(name: "mode", signature: "uiii", types: addr wayland_types[0]),
    wl_message(name: "done", signature: "2", types: addr wayland_types[0]),
    wl_message(name: "scale", signature: "2i", types: addr wayland_types[0]),
    wl_message(name: "name", signature: "4s", types: addr wayland_types[0]),
    wl_message(name: "description", signature: "4s", types: addr wayland_types[0]),
  ]

  wl_output_interface* {.exportc.} = wl_interface(
    name: "wl_output",
    version: 4,
    method_count: 1,
    methods: addr wl_output_requests[0],
    event_count: 6,
    events: addr wl_output_events[0],
  )

  wl_region_requests {.exportc.} = [
    wl_message(name: "destroy", signature: "", types: addr wayland_types[0]),
    wl_message(name: "add", signature: "iiii", types: addr wayland_types[0]),
    wl_message(name: "subtract", signature: "iiii", types: addr wayland_types[0]),
  ]

  wl_region_interface* {.exportc.} = wl_interface(
    name: "wl_region",
    version: 1,
    method_count: 3,
    methods: addr wl_region_requests[0],
  )

  wl_subcompositor_requests {.exportc.} = [
    wl_message(name: "destroy", signature: "", types: addr wayland_types[0]),
    wl_message(name: "get_subsurface", signature: "noo", types: addr wayland_types[90]),
  ]

  wl_subcompositor_interface* {.exportc.} = wl_interface(
    name: "wl_subcompositor",
    version: 1,
    method_count: 2,
    methods: addr wl_subcompositor_requests[0],
  )

  wl_subsurface_requests {.exportc.} = [
    wl_message(name: "destroy", signature: "", types: addr wayland_types[0]),
    wl_message(name: "set_position", signature: "ii", types: addr wayland_types[0]),
    wl_message(name: "place_above", signature: "o", types: addr wayland_types[93]),
    wl_message(name: "place_below", signature: "o", types: addr wayland_types[94]),
    wl_message(name: "set_sync", signature: "", types: addr wayland_types[0]),
    wl_message(name: "set_desync", signature: "", types: addr wayland_types[0]),
  ]

  wl_subsurface_interface* {.exportc.} = wl_interface(
    name: "wl_subsurface",
    version: 1,
    method_count: 6,
    methods: addr wl_subsurface_requests[0],
  )


type wl_display_error* {.size: sizeof(uint32).} = enum
  error_invalid_object = 0
  error_invalid_method = 1
  error_no_memory = 2
  error_implementation = 3
func since*(e: wl_display_error): int =
  case e
  of error_invalid_object: 1
  of error_invalid_method: 1
  of error_no_memory: 1
  of error_implementation: 1
proc isValid*(e: wl_display_error; version: int): bool =
  version >= e.since

type wl_shm_error* {.size: sizeof(uint32).} = enum
  error_invalid_format = 0
  error_invalid_stride = 1
  error_invalid_fd = 2
func since*(e: wl_shm_error): int =
  case e
  of error_invalid_format: 1
  of error_invalid_stride: 1
  of error_invalid_fd: 1
proc isValid*(e: wl_shm_error; version: int): bool =
  version >= e.since

type wl_shm_format* {.size: sizeof(uint32).} = enum
  format_argb8888 = 0
  format_xrgb8888 = 1
  format_c8 = 0x20203843
  format_rgb332 = 0x38424752
  format_bgr233 = 0x38524742
  format_xrgb4444 = 0x32315258
  format_xbgr4444 = 0x32314258
  format_rgbx4444 = 0x32315852
  format_bgrx4444 = 0x32315842
  format_argb4444 = 0x32315241
  format_abgr4444 = 0x32314241
  format_rgba4444 = 0x32314152
  format_bgra4444 = 0x32314142
  format_xrgb1555 = 0x35315258
  format_xbgr1555 = 0x35314258
  format_rgbx5551 = 0x35315852
  format_bgrx5551 = 0x35315842
  format_argb1555 = 0x35315241
  format_abgr1555 = 0x35314241
  format_rgba5551 = 0x35314152
  format_bgra5551 = 0x35314142
  format_rgb565 = 0x36314752
  format_bgr565 = 0x36314742
  format_rgb888 = 0x34324752
  format_bgr888 = 0x34324742
  format_xbgr8888 = 0x34324258
  format_rgbx8888 = 0x34325852
  format_bgrx8888 = 0x34325842
  format_abgr8888 = 0x34324241
  format_rgba8888 = 0x34324152
  format_bgra8888 = 0x34324142
  format_xrgb2101010 = 0x30335258
  format_xbgr2101010 = 0x30334258
  format_rgbx1010102 = 0x30335852
  format_bgrx1010102 = 0x30335842
  format_argb2101010 = 0x30335241
  format_abgr2101010 = 0x30334241
  format_rgba1010102 = 0x30334152
  format_bgra1010102 = 0x30334142
  format_yuyv = 0x56595559
  format_yvyu = 0x55595659
  format_uyvy = 0x59565955
  format_vyuy = 0x59555956
  format_ayuv = 0x56555941
  format_nv12 = 0x3231564e
  format_nv21 = 0x3132564e
  format_nv16 = 0x3631564e
  format_nv61 = 0x3136564e
  format_yuv410 = 0x39565559
  format_yvu410 = 0x39555659
  format_yuv411 = 0x31315559
  format_yvu411 = 0x31315659
  format_yuv420 = 0x32315559
  format_yvu420 = 0x32315659
  format_yuv422 = 0x36315559
  format_yvu422 = 0x36315659
  format_yuv444 = 0x34325559
  format_yvu444 = 0x34325659
  format_r8 = 0x20203852
  format_r16 = 0x20363152
  format_rg88 = 0x38384752
  format_gr88 = 0x38385247
  format_rg1616 = 0x32334752
  format_gr1616 = 0x32335247
  format_xrgb16161616f = 0x48345258
  format_xbgr16161616f = 0x48344258
  format_argb16161616f = 0x48345241
  format_abgr16161616f = 0x48344241
  format_xyuv8888 = 0x56555958
  format_vuy888 = 0x34325556
  format_vuy101010 = 0x30335556
  format_y210 = 0x30313259
  format_y212 = 0x32313259
  format_y216 = 0x36313259
  format_y410 = 0x30313459
  format_y412 = 0x32313459
  format_y416 = 0x36313459
  format_xvyu2101010 = 0x30335658
  format_xvyu12_16161616 = 0x36335658
  format_xvyu16161616 = 0x38345658
  format_y0l0 = 0x304c3059
  format_x0l0 = 0x304c3058
  format_y0l2 = 0x324c3059
  format_x0l2 = 0x324c3058
  format_yuv420_8bit = 0x38305559
  format_yuv420_10bit = 0x30315559
  format_xrgb8888_a8 = 0x38415258
  format_xbgr8888_a8 = 0x38414258
  format_rgbx8888_a8 = 0x38415852
  format_bgrx8888_a8 = 0x38415842
  format_rgb888_a8 = 0x38413852
  format_bgr888_a8 = 0x38413842
  format_rgb565_a8 = 0x38413552
  format_bgr565_a8 = 0x38413542
  format_nv24 = 0x3432564e
  format_nv42 = 0x3234564e
  format_p210 = 0x30313250
  format_p010 = 0x30313050
  format_p012 = 0x32313050
  format_p016 = 0x36313050
  format_axbxgxrx106106106106 = 0x30314241
  format_nv15 = 0x3531564e
  format_q410 = 0x30313451
  format_q401 = 0x31303451
  format_xrgb16161616 = 0x38345258
  format_xbgr16161616 = 0x38344258
  format_argb16161616 = 0x38345241
  format_abgr16161616 = 0x38344241
  format_c1 = 0x20203143
  format_c2 = 0x20203243
  format_c4 = 0x20203443
  format_d1 = 0x20203144
  format_d2 = 0x20203244
  format_d4 = 0x20203444
  format_d8 = 0x20203844
  format_r1 = 0x20203152
  format_r2 = 0x20203252
  format_r4 = 0x20203452
  format_r10 = 0x20303152
  format_r12 = 0x20323152
  format_avuy8888 = 0x59555641
  format_xvuy8888 = 0x59555658
  format_p030 = 0x30333050
func since*(e: wl_shm_format): int =
  case e
  of format_argb8888: 1
  of format_xrgb8888: 1
  of format_c8: 1
  of format_rgb332: 1
  of format_bgr233: 1
  of format_xrgb4444: 1
  of format_xbgr4444: 1
  of format_rgbx4444: 1
  of format_bgrx4444: 1
  of format_argb4444: 1
  of format_abgr4444: 1
  of format_rgba4444: 1
  of format_bgra4444: 1
  of format_xrgb1555: 1
  of format_xbgr1555: 1
  of format_rgbx5551: 1
  of format_bgrx5551: 1
  of format_argb1555: 1
  of format_abgr1555: 1
  of format_rgba5551: 1
  of format_bgra5551: 1
  of format_rgb565: 1
  of format_bgr565: 1
  of format_rgb888: 1
  of format_bgr888: 1
  of format_xbgr8888: 1
  of format_rgbx8888: 1
  of format_bgrx8888: 1
  of format_abgr8888: 1
  of format_rgba8888: 1
  of format_bgra8888: 1
  of format_xrgb2101010: 1
  of format_xbgr2101010: 1
  of format_rgbx1010102: 1
  of format_bgrx1010102: 1
  of format_argb2101010: 1
  of format_abgr2101010: 1
  of format_rgba1010102: 1
  of format_bgra1010102: 1
  of format_yuyv: 1
  of format_yvyu: 1
  of format_uyvy: 1
  of format_vyuy: 1
  of format_ayuv: 1
  of format_nv12: 1
  of format_nv21: 1
  of format_nv16: 1
  of format_nv61: 1
  of format_yuv410: 1
  of format_yvu410: 1
  of format_yuv411: 1
  of format_yvu411: 1
  of format_yuv420: 1
  of format_yvu420: 1
  of format_yuv422: 1
  of format_yvu422: 1
  of format_yuv444: 1
  of format_yvu444: 1
  of format_r8: 1
  of format_r16: 1
  of format_rg88: 1
  of format_gr88: 1
  of format_rg1616: 1
  of format_gr1616: 1
  of format_xrgb16161616f: 1
  of format_xbgr16161616f: 1
  of format_argb16161616f: 1
  of format_abgr16161616f: 1
  of format_xyuv8888: 1
  of format_vuy888: 1
  of format_vuy101010: 1
  of format_y210: 1
  of format_y212: 1
  of format_y216: 1
  of format_y410: 1
  of format_y412: 1
  of format_y416: 1
  of format_xvyu2101010: 1
  of format_xvyu12_16161616: 1
  of format_xvyu16161616: 1
  of format_y0l0: 1
  of format_x0l0: 1
  of format_y0l2: 1
  of format_x0l2: 1
  of format_yuv420_8bit: 1
  of format_yuv420_10bit: 1
  of format_xrgb8888_a8: 1
  of format_xbgr8888_a8: 1
  of format_rgbx8888_a8: 1
  of format_bgrx8888_a8: 1
  of format_rgb888_a8: 1
  of format_bgr888_a8: 1
  of format_rgb565_a8: 1
  of format_bgr565_a8: 1
  of format_nv24: 1
  of format_nv42: 1
  of format_p210: 1
  of format_p010: 1
  of format_p012: 1
  of format_p016: 1
  of format_axbxgxrx106106106106: 1
  of format_nv15: 1
  of format_q410: 1
  of format_q401: 1
  of format_xrgb16161616: 1
  of format_xbgr16161616: 1
  of format_argb16161616: 1
  of format_abgr16161616: 1
  of format_c1: 1
  of format_c2: 1
  of format_c4: 1
  of format_d1: 1
  of format_d2: 1
  of format_d4: 1
  of format_d8: 1
  of format_r1: 1
  of format_r2: 1
  of format_r4: 1
  of format_r10: 1
  of format_r12: 1
  of format_avuy8888: 1
  of format_xvuy8888: 1
  of format_p030: 1
proc isValid*(e: wl_shm_format; version: int): bool =
  version >= e.since

type wl_data_offer_error* {.size: sizeof(uint32).} = enum
  error_invalid_finish = 0
  error_invalid_action_mask = 1
  error_invalid_action = 2
  error_invalid_offer = 3
func since*(e: wl_data_offer_error): int =
  case e
  of error_invalid_finish: 1
  of error_invalid_action_mask: 1
  of error_invalid_action: 1
  of error_invalid_offer: 1
proc isValid*(e: wl_data_offer_error; version: int): bool =
  version >= e.since

type wl_data_source_error* {.size: sizeof(uint32).} = enum
  error_invalid_action_mask = 0
  error_invalid_source = 1
func since*(e: wl_data_source_error): int =
  case e
  of error_invalid_action_mask: 1
  of error_invalid_source: 1
proc isValid*(e: wl_data_source_error; version: int): bool =
  version >= e.since

type wl_data_device_error* {.size: sizeof(uint32).} = enum
  error_role = 0
  error_used_source = 1
func since*(e: wl_data_device_error): int =
  case e
  of error_role: 1
  of error_used_source: 1
proc isValid*(e: wl_data_device_error; version: int): bool =
  version >= e.since

type wl_data_device_manager_dnd_action* {.size: sizeof(uint32).} = enum
  dnd_action_none = 0
  dnd_action_copy = 1
  dnd_action_move = 2
  dnd_action_ask = 4
func since*(e: wl_data_device_manager_dnd_action): int =
  case e
  of dnd_action_none: 3
  of dnd_action_copy: 3
  of dnd_action_move: 3
  of dnd_action_ask: 3
proc isValid*(e: wl_data_device_manager_dnd_action; version: int): bool =
  version >= e.since

type wl_shell_error* {.size: sizeof(uint32).} = enum
  error_role = 0
func since*(e: wl_shell_error): int =
  case e
  of error_role: 1
proc isValid*(e: wl_shell_error; version: int): bool =
  version >= e.since

type wl_shell_surface_resize* {.size: sizeof(uint32).} = enum
  resize_none = 0
  resize_top = 1
  resize_bottom = 2
  resize_left = 4
  resize_top_left = 5
  resize_bottom_left = 6
  resize_right = 8
  resize_top_right = 9
  resize_bottom_right = 10
func since*(e: wl_shell_surface_resize): int =
  case e
  of resize_none: 1
  of resize_top: 1
  of resize_bottom: 1
  of resize_left: 1
  of resize_top_left: 1
  of resize_bottom_left: 1
  of resize_right: 1
  of resize_top_right: 1
  of resize_bottom_right: 1
proc isValid*(e: wl_shell_surface_resize; version: int): bool =
  version >= e.since

type wl_shell_surface_transient* {.size: sizeof(uint32).} = enum
  transient_inactive = 0x1
func since*(e: wl_shell_surface_transient): int =
  case e
  of transient_inactive: 1
proc isValid*(e: wl_shell_surface_transient; version: int): bool =
  version >= e.since

type wl_shell_surface_fullscreen_method* {.size: sizeof(uint32).} = enum
  fullscreen_method_default = 0
  fullscreen_method_scale = 1
  fullscreen_method_driver = 2
  fullscreen_method_fill = 3
func since*(e: wl_shell_surface_fullscreen_method): int =
  case e
  of fullscreen_method_default: 1
  of fullscreen_method_scale: 1
  of fullscreen_method_driver: 1
  of fullscreen_method_fill: 1
proc isValid*(e: wl_shell_surface_fullscreen_method; version: int): bool =
  version >= e.since

type wl_surface_error* {.size: sizeof(uint32).} = enum
  error_invalid_scale = 0
  error_invalid_transform = 1
  error_invalid_size = 2
  error_invalid_offset = 3
  error_defunct_role_object = 4
func since*(e: wl_surface_error): int =
  case e
  of error_invalid_scale: 1
  of error_invalid_transform: 1
  of error_invalid_size: 1
  of error_invalid_offset: 1
  of error_defunct_role_object: 1
proc isValid*(e: wl_surface_error; version: int): bool =
  version >= e.since

type wl_seat_capability* {.size: sizeof(uint32).} = enum
  capability_pointer = 1
  capability_keyboard = 2
  capability_touch = 4
func since*(e: wl_seat_capability): int =
  case e
  of capability_pointer: 1
  of capability_keyboard: 1
  of capability_touch: 1
proc isValid*(e: wl_seat_capability; version: int): bool =
  version >= e.since

type wl_seat_error* {.size: sizeof(uint32).} = enum
  error_missing_capability = 0
func since*(e: wl_seat_error): int =
  case e
  of error_missing_capability: 1
proc isValid*(e: wl_seat_error; version: int): bool =
  version >= e.since

type wl_pointer_error* {.size: sizeof(uint32).} = enum
  error_role = 0
func since*(e: wl_pointer_error): int =
  case e
  of error_role: 1
proc isValid*(e: wl_pointer_error; version: int): bool =
  version >= e.since

type wl_pointer_button_state* {.size: sizeof(uint32).} = enum
  button_state_released = 0
  button_state_pressed = 1
func since*(e: wl_pointer_button_state): int =
  case e
  of button_state_released: 1
  of button_state_pressed: 1
proc isValid*(e: wl_pointer_button_state; version: int): bool =
  version >= e.since

type wl_pointer_axis* {.size: sizeof(uint32).} = enum
  axis_vertical_scroll = 0
  axis_horizontal_scroll = 1
func since*(e: wl_pointer_axis): int =
  case e
  of axis_vertical_scroll: 1
  of axis_horizontal_scroll: 1
proc isValid*(e: wl_pointer_axis; version: int): bool =
  version >= e.since

type wl_pointer_axis_source* {.size: sizeof(uint32).} = enum
  axis_source_wheel = 0
  axis_source_finger = 1
  axis_source_continuous = 2
  axis_source_wheel_tilt = 3
func since*(e: wl_pointer_axis_source): int =
  case e
  of axis_source_wheel: 1
  of axis_source_finger: 1
  of axis_source_continuous: 1
  of axis_source_wheel_tilt: 6
proc isValid*(e: wl_pointer_axis_source; version: int): bool =
  version >= e.since

type wl_pointer_axis_relative_direction* {.size: sizeof(uint32).} = enum
  axis_relative_direction_identical = 0
  axis_relative_direction_inverted = 1
func since*(e: wl_pointer_axis_relative_direction): int =
  case e
  of axis_relative_direction_identical: 1
  of axis_relative_direction_inverted: 1
proc isValid*(e: wl_pointer_axis_relative_direction; version: int): bool =
  version >= e.since

type wl_keyboard_keymap_format* {.size: sizeof(uint32).} = enum
  keymap_format_no_keymap = 0
  keymap_format_xkb_v1 = 1
func since*(e: wl_keyboard_keymap_format): int =
  case e
  of keymap_format_no_keymap: 1
  of keymap_format_xkb_v1: 1
proc isValid*(e: wl_keyboard_keymap_format; version: int): bool =
  version >= e.since

type wl_keyboard_key_state* {.size: sizeof(uint32).} = enum
  key_state_released = 0
  key_state_pressed = 1
func since*(e: wl_keyboard_key_state): int =
  case e
  of key_state_released: 1
  of key_state_pressed: 1
proc isValid*(e: wl_keyboard_key_state; version: int): bool =
  version >= e.since

type wl_output_subpixel* {.size: sizeof(uint32).} = enum
  subpixel_unknown = 0
  subpixel_none = 1
  subpixel_horizontal_rgb = 2
  subpixel_horizontal_bgr = 3
  subpixel_vertical_rgb = 4
  subpixel_vertical_bgr = 5
func since*(e: wl_output_subpixel): int =
  case e
  of subpixel_unknown: 1
  of subpixel_none: 1
  of subpixel_horizontal_rgb: 1
  of subpixel_horizontal_bgr: 1
  of subpixel_vertical_rgb: 1
  of subpixel_vertical_bgr: 1
proc isValid*(e: wl_output_subpixel; version: int): bool =
  version >= e.since

type wl_output_transform* {.size: sizeof(uint32).} = enum
  transform_normal = 0
  transform_90 = 1
  transform_180 = 2
  transform_270 = 3
  transform_flipped = 4
  transform_flipped_90 = 5
  transform_flipped_180 = 6
  transform_flipped_270 = 7
func since*(e: wl_output_transform): int =
  case e
  of transform_normal: 1
  of transform_90: 1
  of transform_180: 1
  of transform_270: 1
  of transform_flipped: 1
  of transform_flipped_90: 1
  of transform_flipped_180: 1
  of transform_flipped_270: 1
proc isValid*(e: wl_output_transform; version: int): bool =
  version >= e.since

type wl_output_mode* {.size: sizeof(uint32).} = enum
  mode_current = 0x1
  mode_preferred = 0x2
func since*(e: wl_output_mode): int =
  case e
  of mode_current: 1
  of mode_preferred: 1
proc isValid*(e: wl_output_mode; version: int): bool =
  version >= e.since

type wl_subcompositor_error* {.size: sizeof(uint32).} = enum
  error_bad_surface = 0
  error_bad_parent = 1
func since*(e: wl_subcompositor_error): int =
  case e
  of error_bad_surface: 1
  of error_bad_parent: 1
proc isValid*(e: wl_subcompositor_error; version: int): bool =
  version >= e.since

type wl_subsurface_error* {.size: sizeof(uint32).} = enum
  error_bad_surface = 0
func since*(e: wl_subsurface_error): int =
  case e
  of error_bad_surface: 1
proc isValid*(e: wl_subsurface_error; version: int): bool =
  version >= e.since

type wl_display_event* {.size: sizeof(uint32).} = enum
  wl_display_event_error
  wl_display_event_delete_id
proc since*(e: wl_display_event): int =
  case e
  of wl_display_event_error: 1
  of wl_display_event_delete_id: 1

type wl_display_request* {.size: sizeof(uint32).} = enum
  wl_display_request_sync
  wl_display_request_get_registry
proc since*(e: wl_display_request): int =
  case e
  of wl_display_request_sync: 1
  of wl_display_request_get_registry: 1

type wl_registry_event* {.size: sizeof(uint32).} = enum
  wl_registry_event_global
  wl_registry_event_global_remove
proc since*(e: wl_registry_event): int =
  case e
  of wl_registry_event_global: 1
  of wl_registry_event_global_remove: 1

type wl_registry_request* {.size: sizeof(uint32).} = enum
  wl_registry_request_bind
proc since*(e: wl_registry_request): int =
  case e
  of wl_registry_request_bind: 1

type wl_callback_event* {.size: sizeof(uint32).} = enum
  wl_callback_event_done
proc since*(e: wl_callback_event): int =
  case e
  of wl_callback_event_done: 1

type wl_compositor_request* {.size: sizeof(uint32).} = enum
  wl_compositor_request_create_surface
  wl_compositor_request_create_region
proc since*(e: wl_compositor_request): int =
  case e
  of wl_compositor_request_create_surface: 1
  of wl_compositor_request_create_region: 1

type wl_shm_pool_request* {.size: sizeof(uint32).} = enum
  wl_shm_pool_request_create_buffer
  wl_shm_pool_request_destroy
  wl_shm_pool_request_resize
proc since*(e: wl_shm_pool_request): int =
  case e
  of wl_shm_pool_request_create_buffer: 1
  of wl_shm_pool_request_destroy: 1
  of wl_shm_pool_request_resize: 1

type wl_shm_event* {.size: sizeof(uint32).} = enum
  wl_shm_event_format
proc since*(e: wl_shm_event): int =
  case e
  of wl_shm_event_format: 1

type wl_shm_request* {.size: sizeof(uint32).} = enum
  wl_shm_request_create_pool
  wl_shm_request_release
proc since*(e: wl_shm_request): int =
  case e
  of wl_shm_request_create_pool: 1
  of wl_shm_request_release: 2

type wl_buffer_event* {.size: sizeof(uint32).} = enum
  wl_buffer_event_release
proc since*(e: wl_buffer_event): int =
  case e
  of wl_buffer_event_release: 1

type wl_buffer_request* {.size: sizeof(uint32).} = enum
  wl_buffer_request_destroy
proc since*(e: wl_buffer_request): int =
  case e
  of wl_buffer_request_destroy: 1

type wl_data_offer_event* {.size: sizeof(uint32).} = enum
  wl_data_offer_event_offer
  wl_data_offer_event_source_actions
  wl_data_offer_event_action
proc since*(e: wl_data_offer_event): int =
  case e
  of wl_data_offer_event_offer: 1
  of wl_data_offer_event_source_actions: 3
  of wl_data_offer_event_action: 3

type wl_data_offer_request* {.size: sizeof(uint32).} = enum
  wl_data_offer_request_accept
  wl_data_offer_request_receive
  wl_data_offer_request_destroy
  wl_data_offer_request_finish
  wl_data_offer_request_set_actions
proc since*(e: wl_data_offer_request): int =
  case e
  of wl_data_offer_request_accept: 1
  of wl_data_offer_request_receive: 1
  of wl_data_offer_request_destroy: 1
  of wl_data_offer_request_finish: 3
  of wl_data_offer_request_set_actions: 3

type wl_data_source_event* {.size: sizeof(uint32).} = enum
  wl_data_source_event_target
  wl_data_source_event_send
  wl_data_source_event_cancelled
  wl_data_source_event_dnd_drop_performed
  wl_data_source_event_dnd_finished
  wl_data_source_event_action
proc since*(e: wl_data_source_event): int =
  case e
  of wl_data_source_event_target: 1
  of wl_data_source_event_send: 1
  of wl_data_source_event_cancelled: 1
  of wl_data_source_event_dnd_drop_performed: 3
  of wl_data_source_event_dnd_finished: 3
  of wl_data_source_event_action: 3

type wl_data_source_request* {.size: sizeof(uint32).} = enum
  wl_data_source_request_offer
  wl_data_source_request_destroy
  wl_data_source_request_set_actions
proc since*(e: wl_data_source_request): int =
  case e
  of wl_data_source_request_offer: 1
  of wl_data_source_request_destroy: 1
  of wl_data_source_request_set_actions: 3

type wl_data_device_event* {.size: sizeof(uint32).} = enum
  wl_data_device_event_data_offer
  wl_data_device_event_enter
  wl_data_device_event_leave
  wl_data_device_event_motion
  wl_data_device_event_drop
  wl_data_device_event_selection
proc since*(e: wl_data_device_event): int =
  case e
  of wl_data_device_event_data_offer: 1
  of wl_data_device_event_enter: 1
  of wl_data_device_event_leave: 1
  of wl_data_device_event_motion: 1
  of wl_data_device_event_drop: 1
  of wl_data_device_event_selection: 1

type wl_data_device_request* {.size: sizeof(uint32).} = enum
  wl_data_device_request_start_drag
  wl_data_device_request_set_selection
  wl_data_device_request_release
proc since*(e: wl_data_device_request): int =
  case e
  of wl_data_device_request_start_drag: 1
  of wl_data_device_request_set_selection: 1
  of wl_data_device_request_release: 2

type wl_data_device_manager_request* {.size: sizeof(uint32).} = enum
  wl_data_device_manager_request_create_data_source
  wl_data_device_manager_request_get_data_device
proc since*(e: wl_data_device_manager_request): int =
  case e
  of wl_data_device_manager_request_create_data_source: 1
  of wl_data_device_manager_request_get_data_device: 1

type wl_shell_request* {.size: sizeof(uint32).} = enum
  wl_shell_request_get_shell_surface
proc since*(e: wl_shell_request): int =
  case e
  of wl_shell_request_get_shell_surface: 1

type wl_shell_surface_event* {.size: sizeof(uint32).} = enum
  wl_shell_surface_event_ping
  wl_shell_surface_event_configure
  wl_shell_surface_event_popup_done
proc since*(e: wl_shell_surface_event): int =
  case e
  of wl_shell_surface_event_ping: 1
  of wl_shell_surface_event_configure: 1
  of wl_shell_surface_event_popup_done: 1

type wl_shell_surface_request* {.size: sizeof(uint32).} = enum
  wl_shell_surface_request_pong
  wl_shell_surface_request_move
  wl_shell_surface_request_resize
  wl_shell_surface_request_set_toplevel
  wl_shell_surface_request_set_transient
  wl_shell_surface_request_set_fullscreen
  wl_shell_surface_request_set_popup
  wl_shell_surface_request_set_maximized
  wl_shell_surface_request_set_title
  wl_shell_surface_request_set_class
proc since*(e: wl_shell_surface_request): int =
  case e
  of wl_shell_surface_request_pong: 1
  of wl_shell_surface_request_move: 1
  of wl_shell_surface_request_resize: 1
  of wl_shell_surface_request_set_toplevel: 1
  of wl_shell_surface_request_set_transient: 1
  of wl_shell_surface_request_set_fullscreen: 1
  of wl_shell_surface_request_set_popup: 1
  of wl_shell_surface_request_set_maximized: 1
  of wl_shell_surface_request_set_title: 1
  of wl_shell_surface_request_set_class: 1

type wl_surface_event* {.size: sizeof(uint32).} = enum
  wl_surface_event_enter
  wl_surface_event_leave
  wl_surface_event_preferred_buffer_scale
  wl_surface_event_preferred_buffer_transform
proc since*(e: wl_surface_event): int =
  case e
  of wl_surface_event_enter: 1
  of wl_surface_event_leave: 1
  of wl_surface_event_preferred_buffer_scale: 6
  of wl_surface_event_preferred_buffer_transform: 6

type wl_surface_request* {.size: sizeof(uint32).} = enum
  wl_surface_request_destroy
  wl_surface_request_attach
  wl_surface_request_damage
  wl_surface_request_frame
  wl_surface_request_set_opaque_region
  wl_surface_request_set_input_region
  wl_surface_request_commit
  wl_surface_request_set_buffer_transform
  wl_surface_request_set_buffer_scale
  wl_surface_request_damage_buffer
  wl_surface_request_offset
proc since*(e: wl_surface_request): int =
  case e
  of wl_surface_request_destroy: 1
  of wl_surface_request_attach: 1
  of wl_surface_request_damage: 1
  of wl_surface_request_frame: 1
  of wl_surface_request_set_opaque_region: 1
  of wl_surface_request_set_input_region: 1
  of wl_surface_request_commit: 1
  of wl_surface_request_set_buffer_transform: 2
  of wl_surface_request_set_buffer_scale: 3
  of wl_surface_request_damage_buffer: 4
  of wl_surface_request_offset: 5

type wl_seat_event* {.size: sizeof(uint32).} = enum
  wl_seat_event_capabilities
  wl_seat_event_name
proc since*(e: wl_seat_event): int =
  case e
  of wl_seat_event_capabilities: 1
  of wl_seat_event_name: 2

type wl_seat_request* {.size: sizeof(uint32).} = enum
  wl_seat_request_get_pointer
  wl_seat_request_get_keyboard
  wl_seat_request_get_touch
  wl_seat_request_release
proc since*(e: wl_seat_request): int =
  case e
  of wl_seat_request_get_pointer: 1
  of wl_seat_request_get_keyboard: 1
  of wl_seat_request_get_touch: 1
  of wl_seat_request_release: 5

type wl_pointer_event* {.size: sizeof(uint32).} = enum
  wl_pointer_event_enter
  wl_pointer_event_leave
  wl_pointer_event_motion
  wl_pointer_event_button
  wl_pointer_event_axis
  wl_pointer_event_frame
  wl_pointer_event_axis_source
  wl_pointer_event_axis_stop
  wl_pointer_event_axis_discrete
  wl_pointer_event_axis_value120
  wl_pointer_event_axis_relative_direction
proc since*(e: wl_pointer_event): int =
  case e
  of wl_pointer_event_enter: 1
  of wl_pointer_event_leave: 1
  of wl_pointer_event_motion: 1
  of wl_pointer_event_button: 1
  of wl_pointer_event_axis: 1
  of wl_pointer_event_frame: 5
  of wl_pointer_event_axis_source: 5
  of wl_pointer_event_axis_stop: 5
  of wl_pointer_event_axis_discrete: 5
  of wl_pointer_event_axis_value120: 8
  of wl_pointer_event_axis_relative_direction: 9

type wl_pointer_request* {.size: sizeof(uint32).} = enum
  wl_pointer_request_set_cursor
  wl_pointer_request_release
proc since*(e: wl_pointer_request): int =
  case e
  of wl_pointer_request_set_cursor: 1
  of wl_pointer_request_release: 3

type wl_keyboard_event* {.size: sizeof(uint32).} = enum
  wl_keyboard_event_keymap
  wl_keyboard_event_enter
  wl_keyboard_event_leave
  wl_keyboard_event_key
  wl_keyboard_event_modifiers
  wl_keyboard_event_repeat_info
proc since*(e: wl_keyboard_event): int =
  case e
  of wl_keyboard_event_keymap: 1
  of wl_keyboard_event_enter: 1
  of wl_keyboard_event_leave: 1
  of wl_keyboard_event_key: 1
  of wl_keyboard_event_modifiers: 1
  of wl_keyboard_event_repeat_info: 4

type wl_keyboard_request* {.size: sizeof(uint32).} = enum
  wl_keyboard_request_release
proc since*(e: wl_keyboard_request): int =
  case e
  of wl_keyboard_request_release: 3

type wl_touch_event* {.size: sizeof(uint32).} = enum
  wl_touch_event_down
  wl_touch_event_up
  wl_touch_event_motion
  wl_touch_event_frame
  wl_touch_event_cancel
  wl_touch_event_shape
  wl_touch_event_orientation
proc since*(e: wl_touch_event): int =
  case e
  of wl_touch_event_down: 1
  of wl_touch_event_up: 1
  of wl_touch_event_motion: 1
  of wl_touch_event_frame: 1
  of wl_touch_event_cancel: 1
  of wl_touch_event_shape: 6
  of wl_touch_event_orientation: 6

type wl_touch_request* {.size: sizeof(uint32).} = enum
  wl_touch_request_release
proc since*(e: wl_touch_request): int =
  case e
  of wl_touch_request_release: 3

type wl_output_event* {.size: sizeof(uint32).} = enum
  wl_output_event_geometry
  wl_output_event_mode
  wl_output_event_done
  wl_output_event_scale
  wl_output_event_name
  wl_output_event_description
proc since*(e: wl_output_event): int =
  case e
  of wl_output_event_geometry: 1
  of wl_output_event_mode: 1
  of wl_output_event_done: 2
  of wl_output_event_scale: 2
  of wl_output_event_name: 4
  of wl_output_event_description: 4

type wl_output_request* {.size: sizeof(uint32).} = enum
  wl_output_request_release
proc since*(e: wl_output_request): int =
  case e
  of wl_output_request_release: 3

type wl_region_request* {.size: sizeof(uint32).} = enum
  wl_region_request_destroy
  wl_region_request_add
  wl_region_request_subtract
proc since*(e: wl_region_request): int =
  case e
  of wl_region_request_destroy: 1
  of wl_region_request_add: 1
  of wl_region_request_subtract: 1

type wl_subcompositor_request* {.size: sizeof(uint32).} = enum
  wl_subcompositor_request_destroy
  wl_subcompositor_request_get_subsurface
proc since*(e: wl_subcompositor_request): int =
  case e
  of wl_subcompositor_request_destroy: 1
  of wl_subcompositor_request_get_subsurface: 1

type wl_subsurface_request* {.size: sizeof(uint32).} = enum
  wl_subsurface_request_destroy
  wl_subsurface_request_set_position
  wl_subsurface_request_place_above
  wl_subsurface_request_place_below
  wl_subsurface_request_set_sync
  wl_subsurface_request_set_desync
proc since*(e: wl_subsurface_request): int =
  case e
  of wl_subsurface_request_destroy: 1
  of wl_subsurface_request_set_position: 1
  of wl_subsurface_request_place_above: 1
  of wl_subsurface_request_place_below: 1
  of wl_subsurface_request_set_sync: 1
  of wl_subsurface_request_set_desync: 1

wayland_types = [
  nil,
  nil,
  nil,
  nil,
  nil,
  nil,
  nil,
  nil,
  addr wl_callback_interface,
  addr wl_registry_interface,
  addr wl_surface_interface,
  addr wl_region_interface,
  addr wl_buffer_interface,
  nil,
  nil,
  nil,
  nil,
  nil,
  addr wl_shm_pool_interface,
  nil,
  nil,
  addr wl_data_source_interface,
  addr wl_surface_interface,
  addr wl_surface_interface,
  nil,
  addr wl_data_source_interface,
  nil,
  addr wl_data_offer_interface,
  nil,
  addr wl_surface_interface,
  nil,
  nil,
  addr wl_data_offer_interface,
  addr wl_data_offer_interface,
  addr wl_data_source_interface,
  addr wl_data_device_interface,
  addr wl_seat_interface,
  addr wl_shell_surface_interface,
  addr wl_surface_interface,
  addr wl_seat_interface,
  nil,
  addr wl_seat_interface,
  nil,
  nil,
  addr wl_surface_interface,
  nil,
  nil,
  nil,
  nil,
  nil,
  addr wl_output_interface,
  addr wl_seat_interface,
  nil,
  addr wl_surface_interface,
  nil,
  nil,
  nil,
  addr wl_output_interface,
  addr wl_buffer_interface,
  nil,
  nil,
  addr wl_callback_interface,
  addr wl_region_interface,
  addr wl_region_interface,
  addr wl_output_interface,
  addr wl_output_interface,
  addr wl_pointer_interface,
  addr wl_keyboard_interface,
  addr wl_touch_interface,
  nil,
  addr wl_surface_interface,
  nil,
  nil,
  nil,
  addr wl_surface_interface,
  nil,
  nil,
  nil,
  addr wl_surface_interface,
  nil,
  addr wl_surface_interface,
  nil,
  nil,
  addr wl_surface_interface,
  nil,
  nil,
  addr wl_surface_interface,
  nil,
  nil,
  nil,
  addr wl_subsurface_interface,
  addr wl_surface_interface,
  addr wl_surface_interface,
  addr wl_surface_interface,
  addr wl_surface_interface,
]


